### PR TITLE
Release 0.4 pull request

### PR DESCRIPTION
**Pull request by ksterne**
Deadline for comments on this is 1700 utc Oct. 29th.  Otherwise, I'll merge it in as we've had this release branch out for over 3 weeks.

### CODE REVIEW

**Comment by asreimer** [comment]
Hey Kevin,

I just reopened the pull request to investigate the source of the merge conflicts. They are not due to the directory structure changes and I didn't expect them to be. When we made the directory structure changes in the rc_params pull request, there wasn't any issue with pulling it in to develop.

The merge conflicts are as follows:

1) CONFLICT (modify/delete): pydarn/sdio/sdDataRead.py deleted in 54d01c718b01b3a400e11b6e3776e0475e28e866 and modified in HEAD. Version HEAD of pydarn/sdio/sdDataRead.py left in tree.

2) CONFLICT (modify/delete): pydarn/sdio/radDataRead.py deleted in 54d01c718b01b3a400e11b6e3776e0475e28e866 and modified in HEAD. Version HEAD of pydarn/sdio/radDataRead.py left in tree.

3) CONFLICT (content): Merge conflict in davitpy/pydarn/radar/radInfoIo.py

These are simple to fix and I do not think it is worth diverging from the branch and pull model to deal with them.

For some reason, 1 and 2 are due to the radDataRead.py and sdDataRead.py files remaining in the old directory structure format... I'll track down why this happened (if you check the current develop branch (https://github.com/vtsuperdarn/davitpy/tree/develop) they aren't there...

3) This is literally the difference between import os, sys and
import os
import sys

    <<<<<<< HEAD:pydarn/radar/radInfoIo.py
        import os, sys
    =======
        import os
        import sys
    >>>>>>> 54d01c718b01b3a400e11b6e3776e0475e28e866:davitpy/pydarn/radar/radInfoIo.py`

Have to TA a lab right now. I'll try to track down the source of 1) and 2) after that.

**Comment by ksterne** [comment]
Hey @asreimer, 

Sounds good on keeping with the pull and merge method.  I think it may get messy, but we'll give it a go.  I'm going through and looking at how painful it is to PEP8 style some code for the radInfoIo.py file.  I just hit the conflict here and I think I've got it resolved.  The way that master has it follows the PEP8 style. 

I'm halfway done PEP8'ing that file though!  If you could look at the other two files, that'd be great!

**Comment by asreimer** [comment]
Ah ok. I've figured it out now.

The answer to the question is in the CONFLICT messages.

    CONFLICT (modify/delete): pydarn/sdio/sdDataRead.py deleted in 54d01c7 and modified in HEAD. Version HEAD of pydarn/sdio/sdDataRead.py left in tree.

Basically, what the conflict message is saying is that while `pydarn/sdio/sdDataRead.py` is being deleted by the pull request, there is a conflict because in the master branch the `sdDataRead.py` file was modified in a different way than what was done in the develop branch. In other words, the history of the file in the master and develop branches is different. Compare the [history of the `sdDataRead.py` file in the master branch](https://github.com/vtsuperdarn/davitpy/commits/master/pydarn/sdio/sdDataRead.py) with the history in the develop branch (pasted below from the command line). Notice they are different. Same thing goes for the `pydarn/sdio/radDataRead.py` file.

This is no big deal. We just need to resolve the merge conflicts via the command line. I can do that tomorrow if I am given the go ahead. 

`sdDataRead.py` relevant history in the develop branch (If you want to know how to look at logs like this [check out this link](https://stackoverflow.com/questions/7203515/how-to-locate-a-deleted-file-in-the-commit-history))

>commit 8f1502159cdbb2e7645b70afbbc13e3267c9acef
>Author: aburrell <ab763@le.ac.uk>
>Date:   Thu Jun 11 10:33:37 2015 +0100
>
>    Improved PEP8 compliance
>    
>    Changed tabbing to comply with pep8, removed hanging spaces
>
>commit aedb2dcfb51e2b53e6277dd6270557cd97e791f3
>Author: Ashton Reimer <ashtonsethreimer@gmail.com>
>Date:   Tue Feb 3 14:21:45 2015 -0600
>
>    Moved modules into a davitpy module in preparation for rcparams. Modified setup.py >accordingly.
>
>commit cb3f223ec089cfa7f9886b0363f299f156339d09
>Author: Ashton Reimer <ashtonsethreimer@gmail.com>
>Date:   Mon Sep 29 12:28:37 2014 -0600
>
>    Removed time_inc from davitpy file fetching/reading.
>
>commit 887f5fb5d19928786d14bf41395f167ed4ae0ebe
>Merge: c2972e9 e0eed4d
>Author: Ashton Reimer <ashtonsethreimer@gmail.com>
>Date:   Fri Aug 29 18:08:12 2014 -0600
>
>    Merged in develop.
>
>commit c2972e9af810a45cd14e00999647f08a6b8691d0
>Author: Ashton Reimer <ashtonsethreimer@gmail.com>
>Date:   Fri Aug 29 18:02:52 2014 -0600
>
>    A pythonic sdDataPtr and implementation of fetchUtils into sdDataRead.py and sdDataTypes.py.
>
>commit e6d8dd3e3bb38df7c839b95ebcd4071160b1261e
>Author: Matthew Wessel <matt.wessel@usask.ca>
>Date:   Thu Aug 28 11:32:46 2014 -0600
>
>    Hotfix: wrong bracket place (#85).
>
>commit e0eed4d5e4da77b4fec066813252586131684b02
>Author: Matthew Wessel <matt.wessel@usask.ca>
>Date:   Thu Aug 28 11:27:27 2014 -0600
>
>    Bug fix: wrong bracket place (#85).
>
>commit cf9b8135d8a9ffddac631cf34ea4b112b2175e82
>Author: Ashton Reimer <ashtonsethreimer@gmail.com>
>Date:   Tue Aug 5 15:46:20 2014 -0600
>
>    Change VTDB environment variable to DB. Also changed new variables names to conform with >PEP8. Started updating documentation.
>
>commit 717699df69b4d57904613bc94c745164f1dbde4a
>Author: Jef Spaleta <jdspaleta@alaska.edu>
>Date:   Tue Jul 22 22:13:11 2014 -0800
>
>    Pythonic radDataPtr
>    Functions in radDataRead are now thin wrappers over methods associated
>    with radDataPtr class.
>    
>    Noteworthy changes:
>    
>    * radDataPtr dmapio now supports seeking to specific dmap record using
>     an index lookup. And rewinding back to the beginning of the ptr object.
>    
>     radDataPtr can now build index of dmap record offset using record
>     datetime as lookup key. Similar scanboundaries can be indexed.
>     Indexing is prereq functionality for interactive data viewer which will
>     allow you, among other things, to point and click on pixels in an fit
>     variable RTI canvas and seek directly to the corresponding rawacf record
>     if available.
>    
>    * python file pointers have been replaced with OS file descriptors to
>     make it possible for C code in dmapio and python code to correctly
>     seek/tell inside an open file. python file pointers, being abstracted
>     python objects don't seek/tell like C FILE pointers. Passing file
>     descriptors into the C code as the underlying representation solves the problem.
>    
>    * Some attributes of radDataPtr have been converted to private
>     attributes to discourage users from interacting with them directly.
>     For example the fd, fp and filename are considered private and are
>     manipulated only via class methods and should not be manipulated
>     directly. As manipulating directly will result in unexpected behavior
>     if fd,fp and filename go out of sync.
>    
>    * functions in radDataRead should continue to work as expected for
>     backwards compatiblility for any code that does not want to take
>     advantage of the radDataptr methods directly.
>    
>     On branch Feature_Python_RadarDataPtr
>     Changes to be committed:
>        modified:   pydarn/rst/src/convert.c
>        modified:   pydarn/rst/src/dmap.c
>        modified:   pydarn/rst/src/dmap.h
>        modified:   pydarn/rst/src/dmapio.c
>        modified:   pydarn/rst/src/rtypes.h
>        modified:   pydarn/sdio/radDataRead.py
>        modified:   pydarn/sdio/radDataTypes.py
>        modified:   pydarn/sdio/sdDataRead.py
>        modified:   pydarn/sdio/sdDataTypes.py
>
>commit b02e1a3af669b856e3c60c023977b72c1312d5fe
>Author: ajribeiro <ajribeiro86@gmail.com>
>Date:   Mon Jun 10 14:30:16 2013 -0400
>
>    completely removed mongo support from radData*, added grid and map file support

**Comment by ksterne** [comment]
Hey @asreimer,  Yes certainly go ahead and get them merged together!  Need to get this done by 1700 utc today.  I may try to take a look at it as well...

**Comment by ksterne** [comment]
Is this further complicated because a lot of the code was moved out of *DataRead and into *DataTypes and fetchUtils for these files?  For sdDataRead.py the master branch got a small bugfix with 3c7e51b .  You can see that this was in the sdDataReadAll function.  However, the release-1.0 branch's sdDataRead.py file doesn't seem to have much for sdDataReadAll.  In the same branch's sdDataTypes.py file, there's a method of readAll listed, but no definition....

Maybe that gets into some more holes that I think we already knew about though....

The conflict with radDataRead.py seems to relate to the recent bugfix that was merged in with #154.  The way this same issue is fixed in the release-1.0 branch happens in another file.  

So does it seem OK to delete the old files from master and go with the release branch's files?  I think for ease, I will still try to copy the current master to the master-old branch.

**Comment by asreimer** [comment]
Hey @ksterne I'll merge these together once we have the ray trace stuff merged in. How does that sound?

The conflict is basically caused because in the develop branch, @jspaleta made the "More pythonic..." commit and then the hotfixes were applied, whereas in the master branch, the hotfixes are the only things that were applied. So the files have different commit histories in the master branch compared with the develop branch.

**Comment by ksterne** [comment]
@asreimer, have you had a chance to look at the ray trace pull request?  Do we want to try to get that in in the next few hours?  As I said before, I propose we do another release for the fall AGU meeting in mid-December for things that don't make it in today.  I wanted to do this release since we are long overdue for having a new master.

Does it hurt to resolve our current conflicts before any other pull requests are merged into release-1.0?  I'm guessing there is the potential for additional conflicts to arise, but it would be good to get current ones resolved sooner than later.

**Comment by asreimer** [comment]
I'm looking at the ray trace pull request right now. 

I don't think the conflicts can be resolved except via the command line with the `git merge` command (so only at merge time).

I agree that we should get another release out before AGU. Seems like we have a few more people able to do some coding now so that should be possible. :)

**Comment by asreimer** [comment]
Does #160 really need to get merged in to this release if we are going to be pushing for another release soon?

I'm voting that we just get this release out now and then work on the next one.

**Comment by ksterne** [comment]
I think I'm agreed here, I know @w2naf was hoping this would get into this release.  I propose though that we make a new release branch in mid-November that hopefully pulls in #160 as well as other pull requests like the refactored RTI and the HWM work @aburrell has going.  Our current master is so off from what we've been working on, I was hoping to get it more in line before adding much more.

**Comment by asreimer** [comment]
First things first though, we should merge the current master in to the `master-old` branch. That's why I've opened pull request #170.

As for the next release branch I think we can do it a bit more cleanly. Namely, I think we should do the following:

1) Freeze pull requests into the develop branch
2) Create a new release branch from the develop branch
3) Test the release branch and make any bug fixes we can find (add whatever polish is needed in terms of PEP8, documentation, etc.)
4) Merge the current master into master-old
5) Merge the release branch into master
6) Merge the new master into the develop branch
7) Unfreeze pull requests into the develop branch

**Comment by asreimer** [comment]
Also, I agree about creating the next release in mid November.

**Comment by ksterne** [comment]
Certainly looks good with the new release protocol.

This is what I've got in trying to do a command line merge:

git merge master
CONFLICT (modify/delete): pydarn/sdio/sdDataRead.py deleted in HEAD and modified in master. Version                                                    master of pydarn/sdio/sdDataRead.py left in tree.
CONFLICT (modify/delete): pydarn/sdio/radDataRead.py deleted in HEAD and modified in master. Version                                                    master of pydarn/sdio/radDataRead.py left in tree.
CONFLICT (modify/delete): pydarn/radar/radInfoIo.py deleted in HEAD and modified in master. Version                                                    master of pydarn/radar/radInfoIo.py left in tree.

It seems as though I may be able to figure out what's going on here after reading through this quick bit:

http://stackoverflow.com/questions/1380670/how-do-i-fix-a-merge-conflict-due-to-removal-of-a-file-in-a-branch

As the message says, I think the issue is that in the release-1.0 branch the file was removed (or in our case moved), yet we've modified it in master.  The modifications to the three files in master seem to be small bugfixes that were also applied to the release files or are no longer applicable since the code has been moved out of the *DataRead files.  

I think I am OK to do with a delete on these three files....what do you think, @asreimer?

**Comment by asreimer** [comment]
Looks to me like you just need to delete the files that are causing the conflict. Do it.

**Comment by ksterne** [comment]
Sorry I was 10 minutes late everyone!  Release branch has been merged into master.

**Comment by asreimer** [comment]
Awesome! I'll make a new tag.

**Comment by asreimer** [comment]
Also, this master will have to be merged into develop now.

**Comment by ksterne** [comment]
I got a new release worked up and out there.  I'll look at the master merge into develop early next week if no one else gets to it first.

**Comment by asreimer** [comment]
I created a pull request #171 to deal with this. Really just needs to be merged and its done.

**Comment by asreimer** [comment]
Ah yes, I see what you mean about already making the new release. 

I edited it to add a summary of changes to it.

**Pull request merged**
