### PR TITLE
update AACGM

### PR DESCRIPTION
**Pull request by aburrell**
Making a vtsuperdarn base version of the pull request for @ksterne.

### CODE REVIEW

**Comment by aburrell** [comment]
TESTS: new AACGM test, replicating Simon's tests and using wrapper functions:

import datetime as dt
from davitpy.models import aacgm
glat = 45.5; glon=-23.5' alt=1135.0; atime=dt.datetime(2014,3,22,3,11)
mlat, mlon, r = aacgm.convert_latlon(glat, glon, alt, atime)
print mlat, mlon, r

48.1896179168 57.7634543568 1.17753288157

aacgm.convert_latlon(mlat, mlon, 1131.097495, atime, "A2G")
(45.44077488032707, -23.47275651809693, 1134.9778957090095)

mlat, mlon, r = aacgm.convert_latlon(glat, glon, alt, stime, "G2A|TRACE")
print mlat, mlon, r
48.194756593 57.7588315442 1.17753288157

aacgm.convert_latlon(mlat, mlon, 1131.097495, atime, "A2G|TRACE")
(45.500001394415754, -23.50000034186013, 1135.000000460991)

aacgm.convert_latlon_arr([mlat], [mlon], [1131.097495], atime, "A2G|TRACE")
(array([45.500001394415754]), array([-23.50000034186013]), array([ 1134.000000460991]))

glat = 37.0; glon = -88.0; alt = 300.0; atime = dt.datetime(2003,5,17,7,53,16)
mlat, mlon, mlt = aacgm.get_aacgm_coord(glat, glon, alt, atime)
print mlat, mlon, mlt
48.8403684174 -17.0060898294 1.97774522265

mlat, mlon, mlt = aacgm.get_aacgm_coord(glat, glon, alt, atime, "COEFF")
print mlat, mlon, mlt
48.8443548299 -16.9994643438 1.9781869217

glon = np.arange(0.0, 20.0, 1.0); glat = np.ones(shape=glon.shape) * 45.0; alt = np.ones(shape=glon.shape) * 150.0
mlat, mlon, mlt = aacgm.get_aacgm_coord_arr(glat, glon, alt, atime, "TRACE")
outlines = ""
for i,gg in enumerate(glon): outlines += "{:.1f} {:.4f} {:.4f} {:.4f}\n".format(gg, mlat[i], mlon[i], mlt[i])
print outlines

0.0 40.2841 76.6676 8.2227
1.0 40.2447 77.4899 8.2775
2.0 40.2108 78.3157 8.3325
3.0 40.1822 79.1452 8.3878
4.0 40.1587 79.9785 8.4434
5.0 40.1400 80.8157 8.4992
6.0 40.1261 81.6569 8.5553
7.0 40.1165 82.5020 8.6116
8.0 40.1111 83.3513 8.6682
9.0 40.1097 84.2048 8.7251
10.0 40.1121 85.0624 8.7823
11.0 40.1179 85.9243 8.8398
12.0 40.1271 86.7904 8.8975
13.0 40.1394 87.6608 8.9555
14.0 40.1546 88.5354 9.0138
15.0 40.1725 89.4143 9.0724
16.0 40.1930 90.2976 9.1313
17.0 40.2157 91.1850 9.1905
18.0 40.2405 92.0768 9.2499
19.0 40.2673 92.9728 9.3097

**Comment by aburrell** [comment]
Tests: AACGM changes implemented through plotUtils, coordUtils (based on plotUtils test):

import davitpy
import pylab as plt
import datetime as dt
f = plt.figure(figsize=(8,4))
ax = f.add_subplot(1,2,1)
ax2 = f.add_subplot(1,2,2)
time = dt.datetime(2014,8,7,18,30)
mag_map = davitpy.utils.plotUtils.mapObj(coords='mag', projection="stere", draw=True,boundinglat=50., lat_0=90., lon_0=0., resolution='l',datetime=time,ax=ax)
mlt_map = davitpy.utils.plotUtils.mapObj(coords='mlt', projection="stere", draw=True,boundinglat=50., lat_0=90., lon_0=0., resolution='l',datetime=time, dateTime=time, ax=ax2)
f.suptitle("Magnetic maps for {:} at {:.0f} km".format(time, mlt_map.altitude))

aacgm_map_example

**Comment by aburrell** [comment]
This pull request replaces #303

**Comment by aburrell** [comment]
Alright, I can't think of anything else more tests to make.  Please do your best to find any bugs!

**Comment by Shirling-VT** [comment]
@aburrell I tested the codes in the new branch and came out with the same results as you posted.

**Comment by aburrell** [comment]
Thank you @Shirling-VT !

**Comment by ksterne** [comment]
Think there's a typo in the first test, stime = atime?

Seems as though there's an import statement missing from the first test.  `import numpy as np` ?

I think most of my numbers agree with what you've posted here in the first test.  However, there does seem to be an issue with the `aacgm.convert_latlon(glat, glon, alt, atime, "G2A|TRACE")` line.  I'm using:
```
x, y, z = aacgm.convert_latlon(glat, glon, alt, atime, "G2A|TRACE")
print x, y, z
```
and I'm getting: 48.1947567594, 57.7588314772, 1.17753288157.  This is pretty close to the result you had, but some of the last few digits are off, which then causes the subsequent "A2G|TRACE" line to be off as well (45.4999996588, -23.5000000101, 1134.999999981.   I think your result agrees more with the calculator provided by Simon at http://sdnet.thayer.dartmouth.edu/aacgm/aacgm_calc.php#AACGM.  Though that only gives 3/4 digits of precision.

I also seem to be a few small digits off on the: `mlat, mlon, mlt = aacgm.get_aacgm_coord(glat, glon, alt, atime)` line.  Here I'm getting 48.8403684093, -17.0060898263, 1.97774522286.

The other numbers I'm getting seem to line up though.  As well, the second test looks pretty good and my figure matches quite well.

Switching to code type of comments, I'm not as familiar with wrapping C code in python, but it seems a little non-pythonic to be passing a conversion code string to determine the type of conversion.  Maybe this just makes things simpler the way it is, but I'd think making methods like `aacgm.convert_aacgm2geo` or `aacgm.convert_geo2aacgm` instead of lumping them all into a `convert_latlon` method.  Maybe it's just a style thing for just me.

In digging here though, I did find some small issues with the documentation that I updated in the `wrapper.py` file.  I'm adding a commit here to update these as well as do some more PEP8 edits on that file.

**Comment by aburrell** [comment]
@ksterne: Your PEP8 changes all look good.  I recommend we merge this, and then add `convert_aacgm2geo` and its counterpart as a separate pull request, if it's decided these are desirable.

**Comment by ksterne** [comment]
OK @aburrell, if you're good with the rounding errors and no one else has an issue then I think it's good to go.  Unfortunately I'm being forced to work from home today and tomorrow.  I'll try to get to merging this later this week or sooner if I run out of my other working-from-home tasks.

**Comment by aburrell** [comment]
Yeah, the rounding error was something I specifically looked into, so I’m ok with it.

Cheers!

**Pull request merged**
