### PR TITLE
Tepidfix raytrace / 2 Parameter Method

### PR DESCRIPTION
**Pull request by w2naf**
- Sets Raytrace ranges out to 4000 km by setting an 8 km horizontal step size.
- Adds 2 notebooks illustrating the 2 Parameter Method Geolocation algorithm [Greenwald et al., 2015, Radio Sci., Submitted]

### CODE REVIEW

**Comment by ksterne** [comment]
Hey, @w2naf, if this is going back into develop, can we leave the README.md file alone so that we have the reminder here to switch to the develop branch when setting things up?  Also, aside from the notebooks, is there a good way to run some simple tests that show the bugfixes?

**Comment by salsrag** [comment]
Kevin,
I did not see this included in your list of changes for release-1.0 or release -0.4 or whatever. I do want to see this included. Thanks

**Comment by w2naf** [comment]
Hi, @ksterne. Yes, we can leave the README.md file alone for the develop branch. I just created a single branch that I am trying to merge into both develop and release-1.0.

I think the best way to test this is to run the raytrace notebook, as well as Ray's new notebooks.

Nathaniel

**Comment by w2naf** [comment]
Hi, Ray (@salsrag).

These changes will appear in the release-1.0 branch as soon as Kevin (or someone else) merges it in. Kevin is planning on testing it himself before he hits the merge button.

Nathaniel

**Comment by MuhammadVT** [comment]
Hi Ray @salsrag <https://github.com/salsrag>,

Would you send me the csv files ('/Desktop/ray_data/*.csv') that are needed
to run your *2Parameter_Plotting.ipynb*? My email is rafiq@vt.edu

Thanks

**Comment by ksterne** [comment]
I ran this just a few minutes ago and I'm getting an error in the analysis notebook on cell 11:

IOError: [Errno 2] No such file or directory: '/home/sd-spare1/Desktop/rays.txt'

I believe this is because there isn't a Desktop directory on this computer.  Is there a better way this file could be stored, such as in /tmp/sd/ where data files are being written anyways?  I think the /tmp/sd/ directory is created whenever data is pulled over, maybe someone check me on that.  If that's the case and we directed this line to the /tmp/sd/ directory, then in theory someone could download davitpy without pulling any data and try to run this code and be in the same spot.  

Also, I think it should be more explicit in noting that the analysis notebook should be run before the plotting notebook.  I do see where there is the requirement in the plotting notebook, but there isn't a simple pointer to the analysis notebook.  Also, if these are paired notebooks, then why is the required .csv file in different locations?  I think to make it easier the file should be in the same location.

**Comment by aburrell** [comment]
I think writing it to the temp directory is a good idea, so long as the rcparam keyword is used and /tmp/sd isn’t hard coded in!

**Comment by w2naf** [comment]
Hi, @ksterne and @aburrell .

I just modified both notebooks so that they read and write from the directory specified by `davitpy.rcParams['DAVIT_TMPDIR']`. I added a note explaining how to change the directory in the notebook.

I also added a notes telling the user that they need to run 2Parameter_Analysis_4000.ipynb before 2Parameter_Plotting.ipynb.

Talk to you later!

Nathaniel

**Comment by MuhammadVT** [comment]
Hi @w2naf <https://github.com/w2naf>, @salsrag <https://github.com/salsrag>

After the fresh installation of davitpy, the two notebook files,
2Parameter_Analysis_4000.ipynb and 2Parameter_Plotting.ipynb, worked fine
in my machine.

Thanks

**Comment by w2naf** [comment]
Wonderful, @MuhammadVT!

Nathaniel

**Comment by ksterne** [comment]
Ok, I've gotten passed the part of writing the output file and see that it's written a file into the /tmp/sd/ directory.  Some more notes here:

Can the cell 13 be cleaned up so that it doesn't generate a huge output?  It creates a huge scroll whenever I've run it.  Maybe there's a way to get the cell from being so large in notebook settings...  

Could cells 14 through 16 be commented to tell what they are doing?

Why are cells 20 commented out without any description?  

Could cells 49, 67, 74, 79 through 83, 86, 88, 89, 98, 99, 100 be taken out?

What is the difference between cells 52 through 54?  It also seems as though there are values that are repeated between the three cells, is it necessary to print all of these out to get the idea?

Can we get titles or axis labels for figures in 90, 91, 92, 94, 97, 101?

That finishes the analysis notebook.  I have to admit, after a lot of those long charts and not much commenting, I was just clicking through and by the time the plots at the end showed up, I'm really not at all sure what I'm looking at or what those mean.  I know I've seen them before and that they show meaningful information, but I can't see it here.

Some of these carry over to the plotting notebook as well, though there are at least axis labels on these figures so I can somewhat tell what I'm supposed to gather from them.  Could titles or maybe a comment at the top of the cell block be added for some of these?

I also am not sure I see the difference or the where the problem was identified with the changes to the fortran code.  I don't know it quite as well, and I trust that the fortran changes are improving things, but I didn't see any numbers running through the notebooks that showed the improvements.  If anything, in some places where numbers were listed towards the end of the notebooks I was seeing numbers change around ever so slightly from what was canned in the notebook.  Is there something simple that I could run on the develop branch and then on the tepidfix_raytrace branch to see in numbers to the fortran code?

**Comment by w2naf** [comment]
Hi, Kevin.  Maybe Ray @salsrag could answer most of these questions.

~Nathaniel

**Comment by asreimer** [comment]
Hey everyone,

I just tested this pull request using notebooks. I was able to run through the notebook without errors, but I have to say that it is hard to see what this notebook is really doing (and therefor if the results I'm getting are expected or not). Here are the plots I obtained using the `2Parameter_Analysis_4000.ipynb` file:
rt
rt_density
rt_scatter
dist1
dist2
dist3
dist4
dist5
dist6


And here's the output plots from the `2Parameter_Plotting.ipynb` file:
dist1
gc1
gc2
comp_gc1
penetrating
grouprange
ratio
dist2
gc3
gc4

**Comment by asreimer** [comment]
@ksterne said:
>That finishes the analysis notebook. I have to admit, after a lot of those long charts and not much commenting, I was just clicking through and by the time the plots at the end showed up, I'm really not at all sure what I'm looking at or what those mean. I know I've seen them before and that they show meaningful information, but I can't see it here.

Unfortunately, this sums it up for me too.

This pull request doesn't have to go out in the release-0.4 does it? It's currently slated for merging into develop.

This seems like a good time to emphasize that in future pull requests we really need to be careful about the commits we add to them. For example, this pull request adds the 2 param method which only uses 2 notebooks and ray tracing, yet there are 8 files that have been modified. This is messy and could cause us problems later in terms of bugs and merge conflicts if we aren't more careful. At the very least, it's confusing while doing testing. 

If there are bugs and formatting to fix, we should open a new pull request and fix them there. Let's try to keep our pull requests on topic to make it easier to test them and prevent merge conflicts and bugs.

**Comment by ksterne** [comment]
Hey @salsrag, 

Did you see some of the questions that I had about the analysis notebook?  There were quite a few extra parts that didn't seem necessary and then plots that I wasn't sure what result I was supposed to get or what I was looking at even.  I have a good list from last Thursday when I was trying to see if we could get this in the 0.4 release.

**Comment by salsrag** [comment]
I am not sure that this is getting to the proper destination. Please respond if you get this.

 

Ray

**Comment by ksterne** [comment]
Hi @salsrag,

Read you loud and clear on that last one.

**Comment by ksterne** [comment]
Hi @salsrag,

Any answers to the feedback that I had a little while ago?  I'm keeping up with this on the pull request web interface on github which also sends you an e-mail.  It might be easier to look at the pull request conversation than sorting through e-mails.

**Comment by ksterne** [comment]
Hello Ray, Nathaniel,

Is there anymore development on this pull request to get it into davitpy?  @asreimer  and I had some comments/questions almost a year ago that haven't been addressed.  If this isn't in in a week, it runs the risk of going over two releases of davitpy.  At which point we should probably timeout this pull request and close it.  No code will be lost, but the request to merge it into our codebase will go away.

**Comment by ksterne** [comment]
I think this one has undergone some more development from this and has gotten stale, so going to close this one for now.

**Pull request closed without merging**
