### PR TITLE
Final release for repo, v0.9

### PR DESCRIPTION
**Pull request by ksterne**
I'm skipping the tradition step of creating and release branch and going straight from develop to master.  Maybe this isn't a good idea since there are merge conflicts here?  Anyone have an opinion on this?

This represents the first release in 2.5 years (wow it's been a while).  I have enabled a Zenodo DOI so that when this is merged and a release is made it can be cited a little better.  I've closed all of the pull request (thanks again for feedback on #358) and all but one issue (relates to deprecation).  Any other parting thoughts that need to be added in before we wrap this up and put it into an archive mode?

If so, please comment in the next week as I'll merge this in (if no one else does) later EDT on the 14th.

### CODE REVIEW

**Comment by ksterne** [comment]
Looks like the merge conflict was only the version number in the `__init__.py` file. I've "fixed" that for now (I've never been great at resolving merge conflicts). So this looks good to go.

**Comment by asreimer** [comment]
Looks fine to me. Once everything with this merge is done (release, Zenodo, etc), next step is to archive the repo.

**Comment by asreimer** [comment]
I'll merge this, then @ksterne you can make the release?

**Comment by ksterne** [comment]
Yea, give me a day and I'll try to get the release out tomorrow then I can archive the repo as well.  Thanks for taking action on this!

**Pull request merged**
