### PR TITLE
Develop: Back FoV

### PR DESCRIPTION
**Pull request by aburrell**
Add functionality to plot the front or rear radar Field-of-View
fov_beam_test
mapoverlay_test_fig

### CODE REVIEW

**Comment by aburrell** [comment]
The sas figure can be made using the __main__ test in mapOverlay
The han figure can be made by:

# Import routines
import datetime as dt
import numpy as np
import pydarn.radar as pyrad
import matplotlib.pyplot as plt
import pydarn.plotting as pp
import mpl_toolkits.basemap as basemap

# Set up the time and location
rad = "han"
stime = dt.datetime(1995, 11, 16)
hard = pyrad.site(code=rad, dt=stime)

# Initialize the figure
f = plt.figure()
ax = f.add_subplot(1,1,1)

# Initialize the map
res_deg = 15.0
height = 111.0e3 * np.ceil((90.0 - 40.0) / res_deg) * res_deg
m = basemap.Basemap(projection='eqdc', width=height, height=height,
                    lat_0=hard.geolat, lon_0=hard.geolon, resolution='l')
m.dateTime=stime

# Draw the map
m.drawcoastlines(linewidth=.5)
m.fillcontinents(color="g", alpha=.1)

# Overlay the radar location, beams, and FoV
pp.overlayRadar(m, codes=rad, dateTime=stime, markerColor="m", markerSize=20, fontSize=20, font_color="m")
pp.overlayFov(m, codes=rad, maxGate=hard.maxgate, lineColor="m", beams=[0,8,15])
pp.overlayFov(m, codes=rad, maxGate=hard.maxgate, fov_dir='back', lineColor="r", beams=[0,8,15])

# Label the figure
f.suptitle("{:s} {:}".format(rad, stime))
ax.text(0.0, hard.geolat, "Beam 0: Front Azim = {:.1f}$^\circ$, Rear Azim {:.1f}$^\circ$".format(hard.beamToAzim(0, fov_dir='front'), hard.beamToAzim(0, fov_dir='back')))

# Show the plot
f.show()

**Comment by aburrell** [comment]
The han plot can be made by:

import datetime as dt
import numpy as np
import pydarn.radar as pyrad
import matplotlib.pyplot as plt
import pydarn.plotting as pp
import mpl_toolkits.basemap as basemap

# Set up the time and location
rad = "han"
stime = dt.datetime(1995, 11, 16)
hard = pyrad.site(code=rad, dt=stime)

# Initialize the figure
f = plt.figure()
ax = f.add_subplot(1,1,1)

# Initialize the map
res_deg = 15.0
height = 111.0e3 * np.ceil((90.0 - 40.0) / res_deg) * res_deg
m = basemap.Basemap(projection='eqdc', width=height, height=height,
                    lat_0=hard.geolat, lon_0=hard.geolon, resolution='l')
m.dateTime=stime

# Draw the map
m.drawcoastlines(linewidth=.5)
m.fillcontinents(color="g", alpha=.1)

# Overlay the radar location, beams, and FoV
pp.overlayRadar(m, codes=rad, dateTime=stime, markerColor="m", markerSize=20, fontSize=20, font_color="m")
pp.overlayFov(m, codes=rad, maxGate=hard.maxgate, lineColor="m", beams=[0,8,15])
pp.overlayFov(m, codes=rad, maxGate=hard.maxgate, fov_dir='back', lineColor="r", beams=[0,8,15])

# Label the figure
f.suptitle("{:s} {:}".format(rad, stime))
ax.text(0.0, hard.geolat, "Beam 0: Front Azim = {:.1f}$^\circ$, Rear Azim {:.1f}$^\circ$".format(hard.beamToAzim(0, fov_dir='front'), hard.beamToAzim(0, fov_dir='back')))

# Show the plot
f.show()

**Comment by aburrell** [comment]
Not sure why this pull request can't be merged automatically.  Just killed and re-inserted these changes for the 3rd time after updating my fork after the kill.  Any suggestions would be welcome.

**Comment by asreimer** [comment]
Hi @aburrell,

I've cherry-picked your commits from this branch that implement the backFov plotting. I've created a branch on the VT repo that includes them. After performing the testing you discuss, I was able to reproduce the plots that you made.

I've made a new pull request to replace this one where I've fixed all the merge conflicts, etc. that were causing problems with this code being merged in. Here's the new pull request: https://github.com/vtsuperdarn/davitpy/pull/137

**Pull request closed without merging**
