### PR TITLE
Enhancement: Replace getJD with more accurate algorithm

### PR DESCRIPTION
**Pull request by asreimer**
Test the code by running getJD with these different inputs: 

    datetime(1,3,2,12)
    datetime(2000,1,1,12)
    datetime(2015,8,4)]
and you should get these outputs:

    expected = [1721486.0,2451545.0,2457238.5]

### CODE REVIEW

**Comment by aburrell** [comment]
with:
``import davitpy``
``import datetime as dt``
``test_time = [dt.datetime(1,3,2,12), dt.datetime(2000,1,1,12), dt.datetime(2015,8,4)]``
``for tt in test_time:``
``    print tt, davitpy.utils.calcSun.getJD(tt)``

And I get the responses you gave.

**Comment by aburrell** [comment]
Testing against astropy, I also get the same answers.

**Comment by asreimer** [comment]
The testing against `astropy` is a great idea.

Good to merge?

**Comment by aburrell** [comment]
Good to merge.

**Pull request merged**
