### PR TITLE
Develop: Back FoV

### PR DESCRIPTION
**Pull request by aburrell**
Added the ability to compute the azimuth/beam and plot the back field-of-view for each radar.  Also improved PEP8 compliance for the selected files.

### CODE REVIEW

**Comment by MuhammadVT** [comment]
Hi Angeline,

There are some merge conflicts in mapOverlay.py file of your pull request
and current develop branch. Could you remove the merge conflict before we
test the pull request?

Thank you.

**Comment by asreimer** [comment]
Hey @aburrell,

I have a couple quick comments:
1) Those revert commits that you have in there scare me a bit (you revived mastermake and then slayed it again!) even though it looks like they don't actually affect any of the code. Could you create a new branch fresh from an up to date develop and then cherry pick your Back FoV commit into that? It would be quick and easy to do and would make it so that I don't have to parse through all of the reverted commits just to make sure nothing has really changed in there that shouldn't have changed.
2) Could you provide usage example or some tips on how to test the new code in this pull request? This can be as simple as adding some testing code to the bottom of the files (after the `__name__ == "__main__"` stuff) so that we can easily verify that we get the same results as you.

Cheers!

**Comment by aburrell** [comment]
Hey @asreimer,

1) Fair enough.  It was a bit of a struggle to revive the Back FoV code... so I Frankensteined it.  I'll give the new branch thing a try, but it'll probably be a while.  If you know of any good web examples that show this I'd appreciate it and that would speed things up.
2) Yeah, meant to have that done by now, but sickness and students have decided differently.  It'll be in place next time.

Question:  Should we kill this pull request and make a new one for the new branch?

**Comment by asreimer** [comment]
Probably good to start a new one. I don't think you can remove the commits too easily. I would recommend branching off of your develop branch when implementing new features or bug fixes.

Here's the commands I would use starting from a fresh copy of the develop branch in the upstream VT repo.

If you have set the VT repo as upstream for your own fork then skip these steps:
1) `git remote add upstream https://github.com/vtsuperdarn/davitpy.git` from within your own fork.

After you have the VT repo set up as upstream:
1) `git checkout -b feature_back_fov upstream/develop` to create the "feature" branch from the develop branch in the upstream VT repo. (https://stackoverflow.com/questions/1783405/checkout-remote-git-branch)
2) `git branch` to check that you are in the `feature_back_fov` branch
3) `git cherry-pick  99d1c1f` to cherry pick the Back FoV commit in to the `feature_back_fov` branch.(https://ariejan.net/2010/06/10/cherry-picking-specific-commits-from-another-branch/)
4) `git push origin feature_back_fov` to push this to online

No worries on the time. Do what you can as you can. Hope you are healthy and stay that way!

**Pull request closed without merging**
