### PR TITLE
0.6 release

### PR DESCRIPTION
**Pull request by ksterne**
Rejoice!  I've finally gotten to an internet connection where I was able to make the 0.6 release branch off of the current develop branch. (Hopefully my git-fu is back!)

Test away all!!!

This merge (and new master release) will take effect in approximately 5 weeks sometime between noon and 3pm Eastern Standard Time on December 8th.

### CODE REVIEW

**Comment by ksterne** [comment]
Looks like I found a typo was introduced during 03bda5f.  I also found a typo in some of the rti.py docstrings where list was spelled lsit.

There's another issue, possibly in the `geoPack.py` code, that's causing out print fit record tool to break.  I'm looking into that now.

**Comment by ksterne** [comment]
Hey @aburrell,

With the new radFov.fov class, I'm finding a few incompatibilities with how the model variable was treated before.  Namely on:
https://github.com/vtsuperdarn/davitpy/blob/0.6-release/davitpy/pydarn/plotting/printRec.py#L174
the model variable is being set to None.  Has the functionality here changed such that it needs to give no value at all to use the default of 'IS'?  I guess in basic terms, did giving None change to giving nothing or 'IS'?

Looking over some more files that bring up the radFov.fov() class, should the documentation at:
https://github.com/vtsuperdarn/davitpy/blob/0.6-release/davitpy/pydarn/plotting/mapOverlay.py#L203
be updated to include the additional models that can be given?

There's a few other places that it shows up, and I would guess for full functionality, we would have the model variable pass through from printRec, mapOverlay, etc. calls.  But...that's another to-do.

I can make the changes here, but I figured I would ask the SME on this code.

**Comment by aburrell** [comment]
Hi @ksterne ,

Good question.  It's not really a change.  If you say None, the other information you supply (such as elevation angle and hop) is given preference.  Beforehand, you could provide elevation angles, specify 'IS', and all backscatter would be treated as ionospheric backscatter with an initial altitude guess determined by the elevation angle.  Now, you can provide a mix of hops and and receive appropriate locations so long as you provide elevation angles and specify None for the model.

Because the overall sentiment hasn't changed (you should use a model if you don't have reliable elevation angles) I didn't update the description at that point.

Does that make sense to you?

**Comment by ksterne** [comment]
Hey @aburrell,

I think that does make sense, but I don't think I formed my question right as it doesn't get at what I'm after.  Maybe this is better:

Before:
model = None -> stuff_happened_1

Now:
model = None -> stuff_happened_2

Does stuff_happened_1 = stuff_happened_2?  I don't think that's true.

Here's the odd thing that I'm seeing:

running
`from davitpy import pydarn
import datetime as dt
s='thisIsMyPrintRec.txt'
pydarn.plotting.printRec.fitPrintRec(dt.datetime(2016,11,14,04,00),dt.datetime(2016,11,14,05,00),'bks',s,fileType=fitacf)`

On master branch, values are filled in for the geo_lat/lon/azm and mag_lat/lon/azm.  Whereas on the 0.6-release 'nan's appear.  For reference, before f36b904 this would just crash.  What's happening is None is being passed in as the model to radFov.fov() in both cases.  So, something has changed here.

I'm guessing to get the 0.6-release branch back to the master functionality (get stuff_happened_1 = stuff_happened_2) is to remove the model=None in the fitPrintRec routine.  I can do that here if you think that makes sense.  I get that this was before your time, mostly that the input to radFov.fov() changed slightly here.  (Also sorry if the majority of this comment seems repetitive, I just saw your edited comment a sentence or two ago)

I think making the change (it's not even a hot/bugfix) to the 0.6 release for the documentation works.

**Comment by ksterne** [comment]
Hey @aburrell,

One other thing here (sorry, I'm not picking you on, but I keep finding these things that you seem to be familiar with)...in:

https://github.com/vtsuperdarn/davitpy/blob/0.6-release/davitpy/pydarn/radar/radFov.py#L674

should we add an error message that the values are getting set to not a number?  It seems as though there's error messages elsewhere in the routine.  I think I get the overall idea of that if statement, but I'm not sure what's being iterated with n.  It seems as though it's trying to get to within a certain accuracy on the height calculation?

I think I hit a random case where I was hitting this nan setting, but had no idea where it was (or still don't know why it was happening).  

I need to get to the other points I raised before...but you know, other projects... I'll try to get to them tomorrow as things are slowly free-ing up.

**Comment by aburrell** [comment]
Hi Kevin,

You’re right to think that the routine is trying to get within a certain accuracy on the height calculation, and is more lenient for 1.5-hop backscatter than 0.5-hop.  

I see no reason not to include an error message (I’d put it at “info” level).  I’m not really sure why I didn’t put one in, it’s a good place for one and always interesting to know how far off the heights were so that you can see whether or not the acceptance criteria should be changed.

Sorry I’m not being more helpful at the moment.  There are things.  So. Many. Things.

Cheers,
Angeline

**Comment by ksterne** [comment]
OK, looks like I've got things cleared up with the printRec issue as well as a few other things.  Did some PEP8 style edits here too that we seemed to be lapsing on!  **REMEMBER TO DO PEP8 EDITS WHEN SUBMITTING A PULL REQUEST!**

Anyways, not a problem @aburrell, on there being so many things going on.  That'll be the fun of doing this pull request right before AGU, everyone else will be busy, busy trying to get ready for that as well as other things.

Maybe some others here can do some testing and get involved.  @Shirling-VT, @MuhammadVT?

**Comment by Shirling-VT** [comment]
@ksterne Sure, but do we have any testing code? Or we just play around and see if it's working well?

**Comment by ksterne** [comment]
The later.  Our development model idea is that this release branch sits out there for a while and gives people a chance to play around with it to see if anything breaks.  In a more ideal world, we would probably have unit test code...but that is TBDone

**Comment by ksterne** [comment]
We're less than 24 hours from a new release of davitpy!!! I hope everyone is excited as I am!  Any major complaints or issues we see with the 0.6 release?  Speak now or...wait for 0.7 release.

I think earlier I noted I would do this at noon EST, but I may not get to it until the early afternoon EST tomorrow.

**Comment by ksterne** [comment]
Any last comments, will merge here in 10 minutes...

**Pull request merged**
