### PR TITLE
Update aacgm

### PR DESCRIPTION
**Pull request by aburrell**
Updated AACGM to version 2 in response to #261 .  Python wrapper is based on that made by @cmeeren .  Unit tests written, but not included in this update because the unit test directory doesn't exist yet :(

The tests included below can also be tested against Simon's online calculator: http://sdnet.thayer.dartmouth.edu/aacgm/aacgm_calc.php

Before testing, be sure to uncomment and fill in the last two lines in the davitpyrc file

TESTS
---------
`import datetime as dt`
`from davitpy.models import aacgm`
`aacgm.convert_latlon(52., 270., 0., dt.datetime(1995,1,1))`

Expecting: (62.80653254470086, -21.045751600077804, 0.9990112144714116)

`aacgm.convert_latlon(52., 270., 600., dt.datetime(2019,1,1))`

Expecting: (62.426195093031446, -17.59949263042519, 1.0931845388119932)

`aacgm.convert_latlon(62.426195093031446, -17.59949263042519, 593.697, dt.datetime(2019,1,1), code="A2G")`

Expecting: (52.00096127179112, -89.99854911726304, 600.0000150946838)

`aacgm.get_aacgm_coord(52., 270., 0., dt.datetime(1995,1,1), method="")`

Expecting: (62.80653254470086, -21.045751600077804, 17.44215243282439)

`aacgm.get_aacgm_coord(52., 270., 600., dt.datetime(2019,1,1), method="")`

Expecting: (62.426195093031446, -17.59949263042519, 17.573266968797466)

`aacgm.get_aacgm_coord(52., 270., 600., dt.datetime(2019,1,1))`

Expecting: (62.42213881345731, -17.59980331822578, 17.573246256277425)

`aacgm.convert_latlon_arr([52.], [270.], [0.], dt.datetime(1995, 1, 1))`

Expecting: ([ 62.80653254], [-21.0457516], [ 0.99901121])

`lats = np.array([-90,-52,-45,0,45,52,90])`
`lons = np.array([-180,-120,-60,-43.1,0,60,120])`
`heights = np.array([0,100,200,300,400,500,600])`
`aacgm.convert_latlon_arr(lats, lons, heights,dt.datetime(2008,1,1))`

Expecting: ([-74.09400879, -44.52621199, -33.76249221, -7.32620931, 41.65889431, 49.5060725, 83.45414167],
[18.93145931, -32.89548348, 8.63894961, 31.73980221, 76.82397498, 133.44903624, 171.13605672],
[0.99773234, 1.01470676, 1.03080871, 1.0481757, 1.06219981, 1.07748898, 1.09190613])

`aacgm.get_aacgm_coord_arr([52.], [270.], [0.], dt.datetime(1995, 1, 1), method="")`

Expecting: ([62.80653254], [-21.0457516], [17.44215243])

`aacgm.get_aacgm_coord_arr(lats, lons, heights, dt.datetime(2008,1,1), method="")`

Expecting: ([-74.09400879, -44.52621199, -33.76249221, -7.32620931, 41.65889431, 49.5060725, 83.45414167],
[18.93145931, -32.89548348, 8.63894961, 31.73980221, 76.82397498, 133.44903624, 171.13605672],
[20.07780862, 16.6226791, 19.3916413, 20.93169814, 23.93730966, 3.71231375, 6.22478178])

`from davitpy import rcParams`
`aacgm.mlt_convert_yrsec(2010, 23607010, 220.0, rcParams['IGRF_DAVITPY_COEFF_FILE'])`

Expecting: 15.54945280583149

### CODE REVIEW

**Comment by ksterne** [comment]
Unable to easily test this since it exists in your repo. :( Can you pull it into a same-name branch on the vtsuperdarn repo?

**Comment by ksterne** [comment]
Nevermind, my git-foo has leveled up!

**Comment by ksterne** [comment]
Get an error of list object has no attribute 'shape' with:
`aacgm.convert_latlon_arr([52.], [270.], [0.], dt.datetime(1995, 1, 1))`

And then numpy isn't defined as np for the array input test.

For `aacgm.get_aacgm_coord_arr([52.], [270.], [0.], dt.datetime(1995, 1, 1), method="")`
get an error output of:
`ERROR:root:Unable to get magnetic lat/lon`
`(None, None, None)`

But the more than one value array works...

**Comment by aburrell** [comment]
Ok @ksterne , fixed those bugs.  Thanks for testing!

**Comment by ksterne** [comment]
Looks like the errors are fixed now.  Thanks for correcting those!

It seems as though a large number of files are changed with this pull request?  Can you reason why this is?  Looking through a few of the changes, it seems like a lot of file deletion and addition here.

A couple of notes looking through the list of files changed:

- In `davitpy/models/aacgm/__init__.py`, why is the functions documentation empty?  Are there no functions here?  Or maybe it's better to be called modules?  
- In the same file, there's a small PEP8 error about whitespace on line 26.  Care to clean that up?  (sorry if it's a bit nit-picky)

**Comment by aburrell** [comment]
The files had to be deleted and readded because: File structure changed and old version had unused rst files included.

Moved unit functions to wrapper.py, seemed a more intuitive place to find them (inspired by cmeseer) and allows for addition of pydarn specific functions in future.

-----Original Message-----

**Comment by aburrell** [comment]
I'll do the white space error this evening,appreciate the pep8 pickiness!

-----Original Message-----

**Comment by aburrell** [comment]
Heh, snuck it in now!  Also checked wrapper.py for pep8 non complience.

**Comment by aburrell** [comment]
Bumping this for second test before merging.  @Shirling-VT , @MuhammadVT , @cmeeren ?

**Comment by Shirling-VT** [comment]
I just tested and got all the expecting results.

**Comment by aburrell** [comment]
Thanks @Shirling-VT !  @ksterne , ok to merge?

**Comment by ksterne** [comment]
I think per our development cycle/guidelines, this should remain unmerged until after the 0.7 release is merged.  Since this hadn't been doubly tested before the 0.7 release branch creation, I do not think we could include this pull request in the 0.7 release either.  I know that its tough to swallow that this won't hit the master branch until later this year, but I don't want to rush this either.

Does that sound OK to you @aburrell?

**Comment by aburrell** [comment]
I’m fine sticking to the development schedule, but in the future I think we should do what we’ve done in the past and make sure there’s a few days of warning/consensus before starting the new release cycle.  That way it would have been possible to get AACGM v2 in the 0.7 release.

**Comment by Shirling-VT** [comment]
Hi  @Angeline,

I find a bug in this update_aacgm branch:
 
 File "/usr/local/lib/python2.7/dist-packages/davitpy-0.6-py2.7-linux-x86_64.egg/davitpy/utils/coordUtils.py", line 255, in coord_conv
    lat, lon, _ = aacgm.aacgmConvArr(list(lat), list(lon), 
AttributeError: 'module' object has no attribute 'aacgmConvArr'

I think this is due to change of attributions in the aacgm module but not being updated in other places which use the old attributes. We may need to double check whether there are other places need to be corrected.

**Comment by aburrell** [comment]
Hi Xueling,

Nice catch.  I looked through the directories looking for aacgm, but clearly didn’t find them all.  Since this pull request is on hold until after the next version update, I’ll fix this after that’s done.

Cheers,
Angeline

**Comment by aburrell** [comment]
Notes: 
1) conflict will be resolved after #317 is merged.  Conflict has arisen from removal of "mlt" plotting.
2) Tests needed for updated routines.
3) Simon made changes to AACGM, so I need include those here.

**Comment by aburrell** [comment]
TESTS: new AACGM test, replicating Simon's tests and using wrapper functions:

`import datetime as dt`
`from davitpy.models import aacgm`
`glat = 45.5; glon=-23.5' alt=1135.0; atime=dt.datetime(2014,3,22,3,11)`
`mlat, mlon, r = aacgm.convert_latlon(glat, glon, alt, atime)`
`print mlat, mlon, r`

48.1896179168 57.7634543568 1.17753288157

`aacgm.convert_latlon(mlat, mlon, 1131.097495, atime, "A2G")`
(45.44077488032707, -23.47275651809693, 1134.9778957090095)

`mlat, mlon, r = aacgm.convert_latlon(glat, glon, alt, stime, "G2A|TRACE")`
`print mlat, mlon, r`
48.194756593 57.7588315442 1.17753288157

`aacgm.convert_latlon(mlat, mlon, 1131.097495, atime, "A2G|TRACE")`
(45.500001394415754, -23.50000034186013, 1135.000000460991)

`glat = 37.0; glon = -88.0; alt = 300.0; atime = dt.datetime(2003,5,17,7,53,16)`
`mlat, mlon, mlt = aacgm.get_aacgm_coord(glat, glon, alt, atime)`
`print mlat, mlon, mlt`
48.8403684174 -17.0060898294 1.97774522265

`mlat, mlon, mlt = aacgm.get_aacgm_coord(glat, glon, alt, atime, "COEFF")`
`print mlat, mlon, mlt`
48.8443548299 -16.9994643438 1.9781869217

`glon = np.arange(0.0, 20.0, 1.0); glat = np.ones(shape=glon.shape) * 45.0; alt = np.ones(shape=glon.shape) * 150.0`
`mlat, mlon, mlt = aacgm.get_aacgm_coord_arr(glat, glon, alt, atime, "TRACE")`
`outlines = ""`
`for i,gg in enumerate(glon): outlines += "{:.1f} {:.4f} {:.4f} {:.4f}\n".format(gg, mlat[i], mlon[i], mlt[i])`
`print outlines`

0.0 40.2841 76.6676 8.2227
1.0 40.2447 77.4899 8.2775
2.0 40.2108 78.3157 8.3325
3.0 40.1822 79.1452 8.3878
4.0 40.1587 79.9785 8.4434
5.0 40.1400 80.8157 8.4992
6.0 40.1261 81.6569 8.5553
7.0 40.1165 82.5020 8.6116
8.0 40.1111 83.3513 8.6682
9.0 40.1097 84.2048 8.7251
10.0 40.1121 85.0624 8.7823
11.0 40.1179 85.9243 8.8398
12.0 40.1271 86.7904 8.8975
13.0 40.1394 87.6608 8.9555
14.0 40.1546 88.5354 9.0138
15.0 40.1725 89.4143 9.0724
16.0 40.1930 90.2976 9.1313
17.0 40.2157 91.1850 9.1905
18.0 40.2405 92.0768 9.2499
19.0 40.2673 92.9728 9.3097

**Comment by aburrell** [comment]
Tests: AACGM changes implemented through plotUtils, coordUtils (based on plotUtils test):

`import davitpy`
`import pylab as plt`
`import datetime as dt`
`f = plt.figure(figsize=(8,4))`
`ax = f.add_subplot(1,2,1)`
`ax2 = f.add_subplot(1,2,2)`
`time = dt.datetime(2014,8,7,18,30)`
`mag_map = davitpy.utils.plotUtils.mapObj(coords='mag', projection="stere", draw=True,boundinglat=50., lat_0=90., lon_0=0., resolution='l',datetime=time,ax=ax)`
`mlt_map = davitpy.utils.plotUtils.mapObj(coords='mlt', projection="stere", draw=True,boundinglat=50., lat_0=90., lon_0=0., resolution='l',datetime=time, dateTime=time, ax=ax2)`
`f.suptitle("Magnetic maps for {:} at {:.0f} km".format(time, mlt_map.altitude))`

aacgm_map_example

**Comment by aburrell** [comment]
This pull request is replaced by #322 .

**Pull request closed without merging**
