### PR TITLE
Field-of-View and HWM14

### PR DESCRIPTION
**Pull request by aburrell**
This branch contains new processing routines to determine the origin field-of-view and propagation path for backscatter, as well as an update to the most recent version of the Horizontal Wind Model.

Tests for these changes are included in the davitpy.pydarn.proc.fov.test_update_backscatter module.  This module contains routines to reproduce all of the figures in the paper submitted to Radio Science.  The second to the last figure demonstrates how changes to the overlay plotting routines were needed to allow radar annotation and beam shading when using subplots.  The last figure uses HWM14.
Since it's not out yet, here are the routines to run to reproduce these figures:

out = davitpy.pydarn.proc.fov.test_update_backscatter.plot_yeoman_plate1()
han_pyk_heater_eval_elv

out = davitpy.pydarn.proc.fov.test_update_backscatter.plot_milan_figure9()
han_groundscatter_eval

out = davitpy.pydarn.proc.fov.test_update_backscatter.plot_storm_figures()

pyk_vel_test_spectral
pyk_vel_map_spectral

out = davitpy.pydarn.proc.fov.test_update_backscatter.plot_meteor_figure()
sas_mscatter_hwm_comp

### CODE REVIEW

**Comment by MuhammadVT** [comment]
Hi

I am getting the following error when I running *out =
davitpy.pydarn.proc.fov.test_update_backscatter.plot_yeoman_plate1()* .
What could be the reason for not finding the data?.
























*Looking locally for fitacf files with radcode: pyk channel: Nonecould not
find fitacf data in local filesLooking locally for fitex files with
radcode: pyk channel: Nonecould not find fitex data in local filesLooking
locally for lmfit files with radcode: pyk channel: Nonecould not find lmfit
data in local filesLooking on the remote SFTP server for fitacf
filesPassword for sd_dbread@sd-data.ece.vt.edu
<sd_dbread@sd-data.ece.vt.edu>: could not find fitacf data on sftp
serverLooking on the remote SFTP server for fitex filesPassword for
sd_dbread@sd-data.ece.vt.edu <sd_dbread@sd-data.ece.vt.edu>: could not find
fitex data on sftp serverLooking on the remote SFTP server for lmfit
filesPassword for sd_dbread@sd-data.ece.vt.edu
<sd_dbread@sd-data.ece.vt.edu>: could not find lmfit data on sftp
serverSorry, we could not find any data for you :(error, your pointer does
not point to any dataERROR:root:update_backscatter ERROR: no data available
in input rad structure *


If I change the date in the plot_yeoman_plate1() from 1998 to 2008, the
code found the data but still giving the following error:

*ERROR:root:update_backscatter ERROR: no data available in input rad
structure *

**Comment by aburrell** [comment]
The database you’re using may not have this period of time.  This should not be happening (all of the mirrors are supposed to be synced) but still does occasionally.  Other time periods would not load data since it’s looking for a particular cp (it’s a special programming mode designed to look at heater-induced irregularities).

**Comment by aburrell** [comment]
Is anyone else going to test this out?  If not I'd like to merge before the branches become too separated.

**Comment by ksterne** [comment]
Hi @aburrell, 

Picking this up since you gave it a bump.  I got @MuhammadVT 's problem here as well.  This isn't a data mirror syncing problem, this is a problem that the test is going back to 1998 and we don't have a way to read fit files right now.  I'm assuming that where you are fitacf files have been created from fit's?  I'm working on updating that for the VT archive so that we have fitacf files from the test period days.  Is there a better test time that is post-20060701 that we could try?

**Comment by ksterne** [comment]
Ok, I've mustered through creating arbitrary filenames in doing a fit to fitacf conversion that are on the sd-data.ece.vt.edu server.  I think I see the issue on why the password is being prompted here since the default on password is True.  I set it to be False, but got an error of:

('fetch_remote_files', "ERROR: can't connect to", 'sd-data.ece.vt.edu', 'with username and password')

In running the first test of .plot_yeoman_plate1(), I'm getting an error of:

proc/fov/update_backscatter.py", line 179, in select_alt_groups
    hmax = scisig.argrelmax(hnum, order=2)[0]
AttributeError: 'module' object has no attribute 'argrelmax'

I've even re-ran (or maybe ran for the first time) the install/debian_dependencies.sh script and got the same error here.. @MuhammadVT maybe you can see if you get the same thing?

It seems as though this is an error relating to the scipy signal module.  Seems as though I'm running scipy version 0.9.0 here, but references online to the .argrelmax function are 0.1x.  I tried adding the line:

sudo pip install --upgrade scipy

as well as:

sudo pip install --upgrade python-scipy

after the apt-get python-scipy line in debian_dependencies.sh, but did not get any good results.  I'm not sure things updated though as I'm still on a scipy version 0.9.0.  @w2naf was describing to me that it may be more intensive for me to get updated to the latest version of everything...any thoughts?  

At least this maybe is a slight step forward?

**Comment by MuhammadVT** [comment]
Hi @aburrell <https://github.com/aburrell>,

As kevin has explained, we do not have the fitacf files for that period of
time. I tried to convert fit files to fitacf files for that period using
fittofitacf routine, but it failed. This may be because there are two files
1998101512fa.fit.bz2,  1998101512f.fit.bz2 instead of 1998101512f.fit.bz2
only. Could you send us the files that are needed to test your pull request?

Thank you.

**Comment by aburrell** [comment]
I tried to do that initially, but they’re too large.  Is there a place I can sftp the files to for you?

**Comment by MuhammadVT** [comment]
If I read the time correctly, we only need the data for 12:00 - 14:00 on
10/15/1998. You may sent it to me at *rafiq@vt.edu <rafiq@vt.edu>*.  If it
exceeds 25Mb (I don't think it is that large), you may share the file with
me through Dropbox or Google Drive.

**Comment by aburrell** [comment]
As I said, it’s too big to send over email.  It’s quite problematic that the VT can’t handle old data.  The rest of the time periods are pretty old too, so I added the fitacf files for them as well (excluding the meteor ablation test).

Leicester doesn’t allow dropbox, so here’s the google drive link.  

https://drive.google.com/folderview?id=0B_eODOjBDFmwM2ZURnl4U29SNkE&usp=sharing <https://drive.google.com/folderview?id=0B_eODOjBDFmwM2ZURnl4U29SNkE&usp=sharing>

Let me know if there’s a problem.

**Comment by aburrell** [comment]
Identifying the problem with scipy is good… if problematic.

What’s your operating system?  I think the upgrade might be painful, but I’m not sure how else to get around it.  I looked into making a local version of that routine, but it’s not simple.

**Comment by MuhammadVT** [comment]
@aburrell <https://github.com/aburrell>, I could be able to test the
following two commands. Please find the the attached figures for the
results.

out = davitpy.pydarn.proc.fov.test_update_backscatter.plot_yeoman_plate1()

out = davitpy.pydarn.proc.fov.test_update_backscatter.plot_storm_figures()

The following two commands can not be tested as we don't have the fitacf
data that are needed in the test code.

out = davitpy.pydarn.proc.fov.test_update_backscatter.plot_milan_figure9()

out = davitpy.pydarn.proc.fov.test_update_backscatter.plot_meteor_figure()


On Fri, Oct 16, 2015 at 10:13 AM, Angeline Burrell <notifications@github.com
> wrote:

> Identifying the problem with scipy is good… if problematic.
>
> What’s your operating system? I think the upgrade might be painful, but
> I’m not sure how else to get around it. I looked into making a local
> version of that routine, but it’s not simple.
>
>

**Comment by aburrell** [comment]
@MuhammadVT , I don't see any of the attachments you mention.  Do they match the test images provided?

**Comment by aburrell** [comment]
I added the file for davitpy.pydarn.proc.fov.test_update_backscatter.plot_milan_figure9() to the google drive.

filename: 19951214.000000.19951215.000000.han.fitacf.gz
drive location: https://drive.google.com/open?id=0B_eODOjBDFmwM2ZURnl4U29SNkE

The routine won't add the text labels showing the different propagation paths to the figure.

**Comment by MuhammadVT** [comment]
I have attached the plots in gmail. Looks like then did not go through. Here I am attaching them in github. 

out = davitpy.pydarn.proc.fov.test_update_backscatter.plot_yeoman_plate1()
plot_yeoman_plate1

out = davitpy.pydarn.proc.fov.test_update_backscatter.plot_storm_figures()
plot_storm_figures_time

plot_storm_figures_maps

out = davitpy.pydarn.proc.fov.test_update_backscatter.plot_milan_figure9()
plot_milan_figure9

I have used 2008 and 2013 data to test 
out = davitpy.pydarn.proc.fov.test_update_backscatter.plot_meteor_figure(), It could find the data but in the end gave me the following error:
reached end of data
ERROR:root:update_backscatter ERROR: no data available in input rad structure.
AttributeError: 'NoneType' object has no attribute 'has_key'

If you send me 2001 data, it would be great.

**Comment by aburrell** [comment]
Alright, these plots are spot on.  It’s nice to see that things are working :->

I’ve added: meteor_ablation_fov.pickle.gz to the google drive.  This file contains data that has already had the field-of-view processed, but since that routine has already been tested what really needs to be looked at is HWM14.  This is what you’ll need to do to use this data:

import davitpy
import cPickle as pickle
beams = pickle.load(open(“meteor_ablation_fov.pickle”, “rb”))
out = davitpy.pydarn.proc.fov.test_update_backscatter.plot_meteor_figure(beams=beams)

**Comment by asreimer** [comment]
I'll give this code a test in the next couple days.

In the mean time, there are many miscellaneous changes included in this pull request. They don't seem to fall under the category of FOV and/or HWM14, so I thought they should be at least highlighted but I have some questions too. I'll enumerate them:

1) `davitpy/__init__.py` is modified (I thought this was to be added to the rc_parameter pull request #141)
2) `davitpy/pydarn/plotting/mapOverlay.py` some of this is PEP8, but what else is happening?
3) `davitpy/pydarn/radar/radUtils.py` label changes for plotting routines. We should have a discussion on what we want for labelling in DaViTpy. I remember you brought up suggestions for plotting labels on the plotACF pull request (https://github.com/vtsuperdarn/davitpy/pull/124#issuecomment-68890436). It's probably time we all decided what to do about plot labels (is there consistent requirements for different journals? If not, how can we make the labels "publication ready"? etc.) This should be it's own pull request.
4) `davitpy/utils/plotUtils.py` - a nice edit to allow a user input axis object to be used.
5) `.gitignore` is changed. We don't really use this, and it shouldn't be a problem if people are using git properly, ie) using `git add <file>` instead of `git commit -a`. But since we are on the topic, should we be using it? What else should go in here?

**Comment by aburrell** [comment]
Thanks for putting it on your list.

The miscellaneous changes were all needed to create the plots for the paper (the ones created in test_update_backscatter).

1) The modification was needed for anything else to work.  I’m a bit surprised #141 hasn’t been pushed yet.

2) There’s a modification similar to (4), which allows a user to specify and input axis.

3) The important change here (needed to run test_update_backscatter) is:
	A) the addition of another parameter (virtual height)
	B) changing the way elevation is identified, to allow names that contain “elv” to all be labeled elevation.

I think we should change the labels and units to be publication ready.  It wouldn’t be hard to expand the dictionaries to have several options (eg long-form names, symbols, AGU unit format, some other unit format).  The alternative is for people to not use this dictionary when making their real plots, which I think would be a waste.

5) .gitignore is changed to ignore autosaved python source files (*.py#).  The default just ignores the (*~) files.  I think it’s just an oversight that this ignore wasn’t there already, since most development file types are already ignored.

I thought it might be useful to include the rc_parameters file in gitignore, since those are edited by everyone individually, but I think that’s overkill.

**Comment by MuhammadVT** [comment]
Angeline,

I could not be able to test plot_meteor_figure. The pickle file is so large
that the command *beams = pickle.load(open(“meteor_ablation_fov.pickle”,
“rb”))  *ran on my machine around two hours. After that  running *out =
davitpy.pydarn.proc.fov.test_update_backscatter.plot_meteor_figure(beams=beams)*
gave me this error:


*Can not find file
/usr/local/lib/python2.7/dist-packages/davitpy-0.2-py2.7-linux-x86_64.egg/davitpy/models/hwm/hwm123114.bin*
I have no idea what this *hwm123114.bin *file is. I want to see whether
Ashton's testing would also be the same.



On Thu, Oct 22, 2015 at 11:31 AM, Angeline Burrell <notifications@github.com
> wrote:

> Thanks for putting it on your list.
>
> The miscellaneous changes were all needed to create the plots for the
> paper (the ones created in test_update_backscatter).
>
> 1) The modification was needed for anything else to work. I’m a bit
> surprised #141 hasn’t been pushed yet.
>
> 2) There’s a modification similar to (4), which allows a user to specify
> and input axis.
>
> 3) The important change here (needed to run test_update_backscatter) is:
> A) the addition of another parameter (virtual height)
> B) changing the way elevation is identified, to allow names that contain
> “elv” to all be labeled elevation.
>
> I think we should change the labels and units to be publication ready. It
> wouldn’t be hard to expand the dictionaries to have several options (eg
> long-form names, symbols, AGU unit format, some other unit format). The
> alternative is for people to not use this dictionary when making their real
> plots, which I think would be a waste.
>
> 5) .gitignore is changed to ignore autosaved python source files (*.py#).
> The default just ignores the (*~) files. I think it’s just an oversight
> that this ignore wasn’t there already, since most development file types
> are already ignored.
>
> I thought it might be useful to include the rc_parameters file in
> gitignore, since those are edited by everyone individually, but I think
> that’s overkill.
>
>

**Comment by aburrell** [comment]
It’s a very large period of time to run, but I’m surprised you couldn’t load the pickle.  It takes about a minute on my machine.  The pickle cuts out half the computer running time, so I hesitate to give you the whole fitacf.

The error looks like you haven’t compiled HWM14 yet.  As with any of the models, the least finicky way is to run setup.py again.  It might be fine to go in and use the local make, though, and not go through all the hassle.

To test hwm14 without running the meteor test, you can just do:

import davitpy
import datetime as dt

stime = dt.datetime(2001, 12, 14)
alt = 100
lat = 0
lon = 0
ap = 4
ihwm = davitpy.models.hwm.hwm_input.format_hwm_input(stime, alt, lat, lon, ap)
davitpy.models.hwm.hwm14(*ihwm)

> Out: array([ 23.58708382, -25.50555992], dtype=float32)

**Comment by asreimer** [comment]
Just a bump @aburrell, I'm going to look at this tonight if I can. Just got a new laptop and returned from a visit in Montreal though so it might not happen tonight. It's near the top of my todo list!

**Comment by MuhammadVT** [comment]
Hi @aburrell,

No matter how many times I redo the compiling,* hwm123114.bin *file is
still couldn't be found in the place where it is supposed to be. I could
have manually copied it to its place, but I will wait for @asreimer's test
results.

Thanks

**Comment by aburrell** [comment]
Hi Muhammad,

I went back and checked the documentation and it looks like the file should be there before you compile.  However, I am also currently looking at the hwm directory for the burrell2015_fov branch on github and the file is there, is the right format, and has the right size.  I don’t know why you don’t have it, but it looks like you had some problems syncing to the branch.  Hopefully @asreimer won’t have the same issues.

Cheers,
Angeline

**Comment by asreimer** [comment]
Ok, here's what I did.

1) Downloaded all of the files in that Google Drive link you posted
2) Set up a directory `/data/{year}/` for each year of files
3) Changed the file names to remove the "end time" in the file names
4) Started up a new python session and imported davitpy, then:

    davitpy.rcParams['DAVIT_LOCAL_DIRFORMAT']='/home/reimer/data/{year}/'
    davitpy.rcParams['DAVIT_LOCAL_FNAMEFMT']='{date}.{hour}.....{radar}.{ftype}'
    out = davitpy.pydarn.proc.fov.test_update_backscatter.plot_yeoman_plate1()

Here's the output that I got (cached because I ran it once before):
>Found cached file: /tmp/sd/19981015.115000.19981015.131000.pyk.fitacf
>WARNING:root:update_beam_fit WARNING: no fit data in beam at 1998-10-15 12:08:29
>
>reached end of data
>Found cached file: /tmp/sd/19981015.115000.19981015.131000.han.fitacf
>
>reached end of data
>WARNING:root:update_beam_fit WARNING: no fit data in beam at 1998-10-15 12:03:21
>
and then I do not get a plot... Any ideas on what I'm doing wrong?

**Comment by aburrell** [comment]
Did you try doing plt.show() after running?

I usually run these after running plt.ion().  I should add a plt.draw()/show() option at the end of the routines.  Give me a sec and I’ll fix that.

**Comment by aburrell** [comment]
Alright, changes pushed to the branch, give it another try.

**Comment by asreimer** [comment]
I did not. Didn't know I had to :) If I run pyplot.show() then I see the plot that I should. 

I've restarted my testing now that you made your edit. I'll post back here with the results.

**Comment by aburrell** [comment]
Yeah, lazy coding on my part!  I’ve been doing plt.ion() first thing… that’s my excuse and I’m sticking too it.

**Comment by asreimer** [comment]
Ok, I was able to reproduce all the same plots. Something interesting to note is that I got some data that was slightly different than @MuhammadVT's plots showed on the fan plots and for the "PYK Beam 0" plots as well.

Trying to run the HWM14 model fails because:
>Can not find file /home/reimer/.local/lib/python2.7/site-packages/davitpy-0.2-py2.7-linux-x86_64.egg/davitpy/models/hwm/hwm123114.bin

This is because the hwm123114.bin file is being compiled as it should be, but isn't being copied into the directory in which davitpy is being installed! Here's how you fix that: in the setup.py file, after the:

>#############################################################################
>#Include the necessary raydarn files
>#############################################################################

but before the:
>#############################################################################
>#Now execute the setup
>#############################################################################

lines, add in the following:
    
    #############################################################################
    #Include the hwm bin files
    #############################################################################
    data_files.append(('davitpy/models/hwm',
                       ['davitpy/models/hwm/hwm123114.bin']))

With this fix implemented, I was able to get the following plot:

figure_1

I'm almost ready to have this merged in. I want to poke around the `update_backscatter.py` file first. Also, nothing can be merged into develop until someone merges #171.

**Comment by asreimer** [comment]
Had a look at the `update_backscatter.py` file. I noticed that the `logging` module is being used here. Reminds me that we should make an effort to get @cmeeren's logging pull request merged in.

@MuhammadVT were you able to get all of your issues resolved? If so, this pull request can be merged in once #171 is. 

@aburrell did a fantastic job of documentation and PEP-8 compliance on this.

**Comment by aburrell** [comment]
Alright, I added the fix to setup.py.  Hopefully this will clear things up.

On a related note, I find it concerning that the data can't be accessed from the VT database.  I changed the test routines to allow file type to be specified something other than "fitacf".  Hopefully this will resolve that issue.

**Comment by aburrell** [comment]
Yes, I changed the way that some points were removed in one of the updates.  I had forgotten to remove ionospheric backscatter with negative powers in the version @MuhammadVT <https://github.com/MuhammadVT> ran.  Well spotted.

**Comment by asreimer** [comment]
>On a related note, I find it concerning that the data can't be accessed from the VT database. I changed the test routines to allow file type to be specified something other than "fitacf". Hopefully this will resolve that issue.

That's because they don't have fitacf files for pre-2006, they only have .fit files (well, actually they have a mix of .fit and fitacf for some radars in 2005 and 2006). It's the same for us here at usask.

**Comment by asreimer** [comment]
Alright, I went back through the comments in this pull request and found that the problems @MuhammadVT had have been resolved (were the same problems I had). See [this comment in particular](https://github.com/vtsuperdarn/davitpy/pull/151#issuecomment-151841870). 

Since everything is good, I'm merging this in now.

**Pull request merged**
