### PR TITLE
Enhancement rc params

### PR DESCRIPTION
**Pull request by w2naf**
Sorry, guys... I accidentally sent a Pull Request to master.  I wanted to send it to develop.  Here it is again.

~Nathaniel
-------------------------------
Hi, everyone!

Ok, the SuperDARN meeting is coming up, and I would really like to see a new version of Master before we go.  Here is a pull request that I think is a step in the right direction.  It's really big, but here are the salient points:

* Ashton's enhancement_rc_params is used as a foundation.
* This does not actually create the rc_params functionality, but it does reorganize everything so you can just do "import davitpy"
* I've tested all of the notebooks and made fixes to make sure they all run with the re-organization.
* Notebooks use the new "%pylab inline" magic to be compatible with the recent iPython 3/Jupyter updates.
* I've made small changes to my MUSIC codes, mostly addressing plotting annotations.
* Ray Greenwald found some bugs in the Raytrace code, and those patches have been added.

Let me know what you think!  I would really like to see this get pushed to develop, then to master within the next few weeks.

All the best,
Nathaniel

### CODE REVIEW

**Comment by asreimer** [comment]
I'll be looking at this tonight!

We need to try to pull in some of the other pull requests too. In particular https://github.com/vtsuperdarn/davitpy/pull/123 needs to be pulled in because file fetching is slightly broken without it.

Also, someone will need to fix the merge conflicts before this can be pulled in. @w2naf do I have your blessing?

**Comment by w2naf** [comment]
Great!  You have my blessing to do any merge-fixing you need.  Please let
me know if you need me to do something.

~Nathaniel

**Comment by asreimer** [comment]
Hey @w2naf, I'm working on adding the rc parameters file now and then I'll work on resolving merge conflicts. I've pulled in all the stuff that you did into my `enhancement_rc_params` branch and when I'm done I'll do a pull request in to yours.

If you have some time, could you have a look at #123? I'll bug @mrwessel and @MuhammadVT too since they both already had a look at that. We should also try to have a look at merging in @aburrell's backFOV stuff.

**Comment by w2naf** [comment]
Thanks, @asreimer.  That sounds great!

Yes, I'll look into those over the next couple days.  I should have some time while some of my longer jobs are running.  It will be super awesome to get this update pulled together!

73,
Nathaniel

**Comment by aburrell** [comment]
Hi @w2naf  and @asreimer ,

I was trying to save the changes I had begun making to resolve inconsistencies between this pull request and develop, but it ended up messing things up.  I've reverted the merge, but the status report is different from what it was.  Can one of you (or someone else) check and make sure that this pull request has reverted to it's previous state before I re-do the fixes?

Cheers,
Angeline

**Comment by w2naf** [comment]
Hi, @aburrell,

This pull request was submitted from a branch on my account, so nothing on it changes unless I make changes to my account.  I think we either need to make a new pull request from the branch on the VTSuperDARN account, or I pull that branch into mine.

I think @asreimer is better at telling you if the VTSuperDARN/w2naf-enhancement_rc_params is fine after you made the reverts.  I just tried merging it into a copy of this pull request, and it failed with conflicts.  I can try resolving those later today if you think I need to.  Otherwise, I can just update this pull request to mirror VTSuperDARN/w2naf-enhancement_rc_params directly.

Let me know!

~Nathaniel

**Comment by asreimer** [comment]
Hey @w2naf and @aburrell,

I can start working on fixing the merge conflicts between this branch and the develop branch. I would like to do that after #123 and #124 are merged though. Can one of you merge them or do I have permission to merge them?

Once that is done, I'll create an `enhancement_rc_params` branch on the VT repo so that we can all work on fixing the merge conflicts more easily, and I'll get started on fixing those issues.

**Comment by w2naf** [comment]
Hi, @asreimer!  I just got back from CEDAR and an exciting ham radio Field Day.  Gareth even got the ePOP satellite to listen for us (http://www.arrl.org/news/canadian-satellite-will-listen-for-arrl-field-day-stations).

I've merged #123 and #124 into develop, so we should be good for working on fixing the merge conflicts on this one.

**Comment by asreimer** [comment]
That's excellent! I'm now VA5ASR. Received my license in the mail last week. I have an old tube HF radio too! Just need an antenna now.

I'm working on fixing the merge conflicts. Keep an eye out for a new pull request.

**Comment by w2naf** [comment]
Congrats!

Remember, simple wire antennas work wonders.

73,
Nathaniel

**Comment by w2naf** [comment]
Hi, @asreimer.

I think we should change the warning message that shows up when davitpyrc cannot be found.  I’ve been coaching a number of new students over the last couple of weeks, and they all get scared off by the message.  I think that the message should include (1) that this is a normal condition of new install and that the default values may be acceptable (2) how and why to create a rc file if you want to change those values.  A lot of these people don’t know what rc files are, too, and so it might be useful to include a note about that.

Take care,
Nathaniel

**Comment by asreimer** [comment]
Good idea. I'll change the warning message to be more informative.

**Comment by w2naf** [comment]
Hey, guys!  Any more progress on getting this merged?

Thanks,
Nathaniel

**Comment by asreimer** [comment]
Hey @w2naf, 
I've been working on it, but I had to drop it last week (home renos, weddings, etc). Picking it back up today.
Sorry about the delay. I really want to get this done sooner rather than later!

**Comment by asreimer** [comment]
So I've created an enhancement_rc_params branch on the VT repo now. I've also created a pull request where all merge conflicts are resolved (#141). Probably safe to close this pull request.

**Pull request merged**
