### PR TITLE
Unit Testing for DaViT-py

### PR DESCRIPTION
**Pull request by asreimer**
It's finally started! We now have a branch for adding unit tests to DaViT-py! [You can read more about unit testing here](https://docs.python.org/2/library/unittest.html). Basically, unit testing will speed up and make our pull request testing process far more thorough. Once all the unit tests are built for our codebase, unit tests can be used to check if a pull request against the entire davitpy repository!

Eventually we can even do [unit testing on figures generated from data files](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/tests/test_png.py) to ensure our plotting hasn't been broken by a pull request. [Matplotlib](https://github.com/matplotlib/matplotlib/tree/master/lib/matplotlib/tests) has tons of unit tests you can look at as examples.

Unit testing is a technique of Test Driven Development. There's lots of resources online to read about this, but IMO (this page is particularly useful](http://docs.python-guide.org/en/latest/writing/tests/).

Not all unit tests have been added to this pull request yet. I've added this pull request now with the hope that others will help me develop all the unit tests that remain to be built (specifically, if you built a function and really understand how it works you are the best person to build a unit test for it!). 

The important thing to remember in building a unit test is to be thorough in testing different test cases. This means that if a function include various optional arguments, you should build your unit test to test them all. Each test unit should also focus on a tiny bit of the codebase and prove that it works. For us, I think this means one should have a unit test for each function in our codebase (correct me if I'm wrong!).

I made the decision to keep our testing simple. Everything is built off of the `unittest` library in python. Here's how you add your own unit test:
1) Create a `test_name.py` file in the `davitpy/tests` directory and build your unit test in there. Here's a basic skeleton for such a file:

```
import unittest
from davitpy.whatever import *

class TestAacgmConv(unittest.TestCase):
    def test_aacgmConv_0km_1995(self):
        expected = 'foo'
        output = some_function_in_davitpy.whatever
        self.assertEqual(output, expected)
```

2) Add the test to the `tests.py` file in the root directory of the repo. This is done by appending `'davitpy.tests.test_name'` to the `default_test_modules` list at the beginning of the file.

3) Run all unit tests. This is done by executing the command `python tests.py` in the root directory of the repo. **First, make sure you run `python setup.py install` or your flavour of that command!** When you run this command you should see something like this:

> Loaded davitpyrc file from DaViTpy installation directory. Path: /home/ashtonsethreimer/davitpy/davitpy
> test_aacgmConv_0km_1995 (davitpy.tests.test_aacgm.TestAacgmConv) ... ok
> test_aacgmConv_600km_2002 (davitpy.tests.test_aacgm.TestAacgmConv) ... ok
> test_aacgmConv_600km_2002_from_aacgm_to_geo (davitpy.tests.test_aacgm.TestAacgmConv) ... ok
> test_aacgmConvArr_0km_1995_len1_input (davitpy.tests.test_aacgm.TestAacgmConvArr) ... ok
> test_aacgmConvArr_2008_len7_input (davitpy.tests.test_aacgm.TestAacgmConvArr) ... ok
> test_mltFromEpoch_mlon220 (davitpy.tests.test_aacgm.TestMltFromEpoch) ... ok
> test_mltFromEpoch_mlon45 (davitpy.tests.test_aacgm.TestMltFromEpoch) ... ok
> test_mltFromYmdhms_mlon220 (davitpy.tests.test_aacgm.TestMltFromYmdhms) ... ok
> test_mltFromYmdhms_mlon45 (davitpy.tests.test_aacgm.TestMltFromYmdhms) ... ok
> test_mltFromYrsec_mlon220 (davitpy.tests.test_aacgm.TestMltFromYrsec) ... ok
> test_mltFromYrsec_mlon45 (davitpy.tests.test_aacgm.TestMltFromYrsec) ... ok
> test_coordConv_redirection (davitpy.tests.test_coordUtils.TestCoordConv) ... coordConv has been >renamed coord_conv and dateTime has
> been renamed date_time for PEP 8 compliance.  Please use
> those from now on.  Also altitude is now optional.
> ok
> test_coord_conv (davitpy.tests.test_coordUtils.TestCoordConv) ... ok
> test_coord_conv_array (davitpy.tests.test_coordUtils.TestCoordConv) ... ok
> test_coord_conv_list (davitpy.tests.test_coordUtils.TestCoordConv) ... ok
> test_coord_conv_mlt_altitudes (davitpy.tests.test_coordUtils.TestCoordConv) ... ok
> test_coord_conv_mxn_array (davitpy.tests.test_coordUtils.TestCoordConv) ... ok
> test_coord_conv_wrong_input (davitpy.tests.test_coordUtils.TestCoordConv) ... ok
> test_calcDistPnt (davitpy.tests.test_geoPack.TestGeoPack) ... ok
> test_gcarToLcar (davitpy.tests.test_geoPack.TestGeoPack) ... ok
> test_geodToGeoc (davitpy.tests.test_geoPack.TestGeoPack) ... ok
> test_geodToGeocAzEl (davitpy.tests.test_geoPack.TestGeoPack) ... ok
> test_greatCircleAzm (davitpy.tests.test_geoPack.TestGeoPack) ... ok
> test_greatCircleDist (davitpy.tests.test_geoPack.TestGeoPack) ... ok
> test_greatCircleMove (davitpy.tests.test_geoPack.TestGeoPack) ... ok
> test_gspToGcar (davitpy.tests.test_geoPack.TestGeoPack) ... ok
> test_lspToLcar (davitpy.tests.test_geoPack.TestGeoPack) ... ok
> test_hwm (davitpy.tests.test_hwm.TestHWM) ... ok
> ---
> 
> Ran 28 tests in 0.043s
> 
> OK

### CODE REVIEW

**Comment by MuhammadVT** [comment]
Hi @asreimer 

Wow, you have added a lot of test codes in this pull request. I really appreciate it.

After running python test.py:
test_hwm (davitpy.tests.test_hwm.TestHWM) ... FAIL
  
I got an AssertionError in line 60. Here is what I got:
Traceback (most recent call last):
  File "/home/muhammad/softwares/mydavitpy/davitpy/tests/test_hwm.py", line 60, in test_hwm
    self.assertEqual(output, expected)
AssertionError: ..........................  

Besides adding test codes, I see you editing davitpy/models/hwm/checkhwm14.pyf,   davitpy/utils/calcSun.py as well. How these are related to the unit testing?

**Comment by asreimer** [comment]
Hey @MuhammadVT,

Yes, I should have talked about those edits to HWM and to `calcSun.py`. First `calcSun.py`: while writing unit tests for the methods in this file, I found the calcJD method wasn't accurate, so I fixed it ([see this commit](https://github.com/vtsuperdarn/davitpy/commit/034f4a378ad95187d6429b92f59b9614eb335176)). As for the `checkhwm14` stuff, I added the fortran routines that are made by the people who developed HWM14 for testing the output of HWM14 (why write our own testing routines when they are provided :P).

Now we just need to write some more unit tests! I'm going to try to implement something that can check figures produced by our code so we can unit test some standard plots (rti, fan plot, etc.).

**Comment by asreimer** [comment]
MSIS now has a unit test for it. I wrapped the fortran testing code that ships with the MSIS source code and have implemented it as the unit test (similar to what was done for HWM).

**Comment by MuhammadVT** [comment]
Hey @asreimer ,

I have tested this on my machine (ubuntu 12.04) and clean installation of ubuntu 14.04 as well, and got the same following error. 

======================================================================
FAIL: test_hwm (davitpy.tests.test_hwm.TestHWM)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/muhammad/softwares/mydavitpy/davitpy/tests/test_hwm.py", line 60, in test_hwm
    self.assertEqual(output, expected)
AssertionError:...........................................


By the way, this pull request has merge conflicts to be resolved.

**Comment by asreimer** [comment]
Things have changed since I made this pull request. I'll have to sort it out.

**Comment by asreimer** [comment]
I've fixed the merge conflicts.

@MuhammadVT, you need to run `python setup.py install --user` or your flavour of that command before running the unit tests. Once you do this, the error you encountered will go away.

**Comment by asreimer** [comment]
There are some substantial merge conflicts in this branch right now. I'll fix those and then maybe we can work on getting unit testing fully implemented (at least on the core stuff)? Would love for this to be included into the 0.6 release. Makes testing our code sooooo much easier.

**Comment by scivision** [comment]
this should be integrated with #312

**Comment by ksterne** [comment]
Closing this for now in prep for archiving and finishing deprecation of this repo.

**Pull request closed without merging**
