### PR TITLE
RTI Plotting Refactoring

### PR DESCRIPTION
**Pull request by asreimer**
This pull request fixes a few issues with the RTI plotting and also refactors the code into a more modular form. The refactoring allows one to make custom RTI plots much more easily than could be done in the past. 

One major issue that has been fixed is the x-axis labeling. Time is now properly displayed and formatted according to whether the data crosses changes in date or multiple days.

Some variable names have been updated, but to prevent this from breaking anyone's existing code I've added a deprecation warning and a temporary wrapper. Specifically, `plotRti` is being deprecated in favour of `plot_rti`.

To test this code run the following 3 commands and compare your figures with mine:

1) `f = pydarn.plotting.plotRti(datetime(2012,11,26,15),'kod',eTime=datetime(2012,11,27,2),channel='all',params=['velocity','velocity_error'],coords='mag')`

you should see a deprecation warning too!

2) `f = pydarn.plotting.plot_rti(datetime(2012,11,25),'kod',eTime=datetime(2012,11,27),channel='all',params=['velocity','velocity_error'],coords='gate')`

3) `f = pydarn.plotting.plotRti(datetime(2012,11,25),'kod',eTime=datetime(2012,11,25,15),channel='all',params=['power'],coords='geo')`

1)
figure_1
2) 
figure_2
3)
figure_3

### CODE REVIEW

**Comment by asreimer** [comment]
This pull request *could* be used to fix bug https://github.com/vtsuperdarn/davitpy/issues/120. I can do this tomorrow.

**Comment by MuhammadVT** [comment]
Hi

I have tested the three commands for this pull request and got the expected
results. But the bug in #120
<https://github.com/vtsuperdarn/davitpy/issues/120> is still not been fixed
by this pull request yet. Also, it would be nicer if the y-axis ticks for
latitudes are located at integer points instead of floating points.

Thanks

**Comment by MuhammadVT** [comment]
Hi again,

I have just found a bug in the cold. if you run
f = pydarn.plotting.plotRti(datetime(2012, 11, 26, 15), 'kod',
eTime=datetime(2012, 11, 27, 2), channel='all', params=['velocity'],
coords='mag', scales=[-400, 400])
it gives error message. It is because when "params" is set to a single
value like ['velocity'], len(params) = 1 but len(scales) = 2, which
violates the assertion in line 128

However, running it in the following way fix the problem
f = pydarn.plotting.plotRti(datetime(2012, 11, 26, 15), 'kod',
eTime=datetime(2012, 11, 27, 2), channel='all', params=['velocity'],
coords='mag', scales=[[-400, 400]])

So, the easiest way to fix the bug might be to make the "scales" argument
as nested list even when "params" is set to a single parameter.

Thanks

**Comment by asreimer** [comment]
Bug #120 is now fixed with my latest commit. Here's the figure that I get with davitpy:

figure_1

and here's what you get with the VT website:

rti

The only difference is the coordinates are a bit different. I attribute this to the fact that AACGM in DaViTpy has been patched to fix an error with the wrong coefficients file being loaded. I suspect the VT website is using AACGM without that fix.

**Comment by asreimer** [comment]
Hey @MuhammadVT 

The bug you found is not a bug, however, the asserts could be clearer. I've added an assert that makes sure that scales is input they way it needs to be, but provides a clear error message if it isn't.

I have modified the formatting for the yaxis on the RTI panels. Should be better now!

**Comment by MuhammadVT** [comment]
Hi @asreimer

I came across a few minor issues in the refactored rti.py while I was about
to merge this pull request. Here are the list:

1) in line 749, the comment does not match with content. Shouldn't it be *#plot
the nave data*  ?
2) in line 750, it should be *fmt='k:'* instead of
*fmt='k-'*
3) The **Args** in some functions do not match with the corresponding
functions' actual arguments. Would you mind going over all the ""Args"" and
delete extra arguments?

After this, we should merge this to the new release.

Thanks

**Comment by ksterne** [comment]
Hey @asreimer,

You'll see the several commits I added to PEP8 style the rti.py file.  I also made the simple edit that @MuhammadVT noted on the number of averages.  Maybe just a copy and paste fail there.  I re-ran through all of the 4 test (the 3 you mentioned and the fix for #120 ) and it looks like they are check out.  Do you want to make sure I didn't mess anything up with the PEP8 styling?  I'll wait to merge after one last look through.

**Comment by asreimer** [comment]
Hey @ksterne and @MuhammadVT. I have checked all the code after the PEP-8 edits and everything still works. I have also cleaned up the documentation as requested. 

Run through the tests in my original post and see if everything is working for you.

**Comment by MuhammadVT** [comment]
I have run through the following commands, and the results are as expected.

1) f =
pydarn.plotting.plotRti(datetime(2012,11,26,15),'kod',eTime=datetime(2012,11,27,2),channel='all',params=['velocity','velocity_error'],coords='mag')

2) f =
pydarn.plotting.plot_rti(datetime(2012,11,25),'kod',eTime=datetime(2012,11,27),channel='all',params=['velocity','velocity_error'],coords='gate')

3) f =
pydarn.plotting.plotRti(datetime(2012,11,25),'kod',eTime=datetime(2012,11,25,15),channel='all',params=['power'],coords='geo')

4) fig=pydarn.plotting.rti.plotRti(datetime(2013,3,17,11,50),'cvw',datetime(2013,3,17,14,0),bmnum=4,params=['velocity'],coords='mag')

We can go ahead and merge this.


Thanks

**Pull request merged**
