### PR TITLE
Bug Fix: Indentation error breaking terminator plotting

### PR DESCRIPTION
**Pull request by asreimer**
Basically exactly what the title says. In refactoring the rti code I messed up the indentation. Run the following code to test that the terminator plotting is fixed.

    from davitpy.pydarn.plotting import plot_rti
    from datetime import datetime,timedelta
    stime = datetime(2014,7,10)
    etime = stime+timedelta(days=1)
    fig = plot_rti(stime,'sas',params=['elevation'],coords='geo',bmnum=2,eTime=etime,fileType='fitacf',plot_terminator=True)

### CODE REVIEW

**Comment by ksterne** [comment]
So, seems as though the indent is off by one space.  Also...can you repull from the latest develop?  This pull request doesn't include any of the PEP8 edits I made on it.

**Comment by ksterne** [comment]
@asreimer, this may be have been a "seat of the pants" pull request on the tail end of AGU.  Be careful to repull the latest develop as the original version didn't even include the fix for the missing elevation angle data.  I think I've got things corrected up now...can you confirm?

**Comment by MuhammadVT** [comment]
It is working fine here.

**Comment by asreimer** [comment]
Hey, I'll give it a quick test.

For context, I think I made this pull request before the other fixes were merged, that's why it didn't have the other fixes in it. Thanks for updating the branch @ksterne!

**Comment by asreimer** [comment]
Works for me. There is a weird thing happening to the terminator when the CPID changes, but that can be the subject of another pull request.

**Pull request merged**
