### PR TITLE
Tepidfix raytrace / 2 Parameter Method

### PR DESCRIPTION
**Pull request by w2naf**
* Sets Raytrace ranges out to 4000 km by setting an 8 km horizontal step size.
* Adds 2 notebooks illustrating the 2 Parameter Method Geolocation algorithm [Greenwald et al., 2015, Radio Sci., Submitted]

### CODE REVIEW

**Comment by salsrag** [comment]
Nathaniel,

 

There is one issue in your commit summary. This version does not work on Southern-Hemisphere radars. You have to be careful with the magnetic field geometry in the Southern Hemisphere. I played with it a bit, but wasn’t sure it was working correctly, so I set it aside. 

 

Ray

**Comment by w2naf** [comment]
Does this apply to your 2 Parameter Method Notebooks only? Or does this also apply to the raytrace code itself?

Nathaniel

**Comment by salsrag** [comment]
I am pretty sure it applies to the two parameter analysis only. I will look at the code again to remember wha the exact issues are.

 

Ray

**Comment by asreimer** [comment]
Closing this since it is essentially a duplicate of #160 now that the 0.4-master release has gone out.

**Pull request closed without merging**
