### PR TITLE
0.5-release

### PR DESCRIPTION
**Pull request by asreimer**
This is the pull request for the 0.5-release.

This release includes:
1) RTI plotting improvements and bugfixes
2) Upgrade to HWM14 from HWM07
3) FOV categorization code (@aburrel's method)
4) More PEP8 compliance edits

Still remaining to be done (the only commits allowed to this branch):
1) Change docstring style to numpy format (i.e. http://sphinxcontrib-napoleon.readthedocs.org/en/latest/example_numpy.html)
2) Implement logging instead of print statments

Happy coding!

### CODE REVIEW

**Comment by asreimer** [comment]
I've added a 'verbosity' key to the `davitpyrc` file and to `defaultParams` in the `rcsetup.py` file. Here's the details as documented in the rc file:

    ####
    # VERBOSITY
    # Valid levels are silent, helpful, debug, and debug-annoying. These 
    # correspond to the logging module logging levels of 60, 30, 20, and
    # 10. See https://docs.python.org/2/howto/logging.html for more info.
    verbosity : helpful

Default is set to "helpful". The intent here was that silent should never output anything, helpful should output information that a user might like to see regularly (critical, warnings, errors), debug should include a bit more information (such as "fetching files..." type messages), debug-annoying should say everything (detailed step-by-step of what davitpy is doing).

**Comment by ksterne** [comment]
Sounds good on adding the verbosity variable.  We'll have to add a lot of import davitpy lines to files here...or is there another way to set a global variable?  

I'm a little bit of a newbie to logging; I just made a commit to the radDataTypes file with something that looks like what you were describing.  Is this what you were thinking @asreimer?  I didn't want to get too far without some kind of feedback.

**Comment by asreimer** [comment]
Hey @ksterne, we shouldn't have to add any import davitpy statements. I think all we have to do is add an import logging to the `__init__.py` file in the `davitpy` directory and then have it set the logging level using the rcParams dictionary. 

If I understand it correctly, if you use the `logging.info()` method and the logging level isn't set to show `info` then nothing is displayed, so the if statements are not needed. I'll test this out and report back.

**Comment by aburrell** [comment]
That’s true.  logging.info <http://logging.info/>, logging.warning, logging.error are all used to set different levels so that no if statements are needed.

**Comment by ksterne** [comment]
Alright, thanks for setting me straight there some.  Been looking at how to get things in the `__init__.py` file.  But looking around at it, I noticed there's some 2 space indents at the end and some extra white spaces.  I also noticed there's a `__version__` variable in there that's set to 0.3.  Is this necessary since we set a version in the `setup.py` code?

Otherwise, I can't seem to make much sense of adding the logging level in the `__init__.py` code.  Though I haven't given it a good try yet.

**Comment by asreimer** [comment]
There. I've made it quite easy now actually. All one needs to do is include an `import logging` in each file in davitpy. The logger is set up when the `verbosity` key is set in the `rcParams` dictionary. I've made it so that if someone changes the verbosity it updates the logging level too!

So in summary, all one needs to do is put an `import logging` statement in each file and then start replacing the print statements.

Here's what I propose for when making decisions on what print statements should be converted to:
1) logging.warning, logging.error, logging.exception == helpful (what a typical user would want to see)
2) logging.info == debug (basic debug info that a user may want to see if they like a bit more verbosity than with helpful)
3) logging.debu == debug-annoying (for everything else that most people never want to see and would simply clutter up the screen)

**Comment by asreimer** [comment]
One question: Do we want to replace `warnings.warn` with `logging.warning`?

**Comment by aburrell** [comment]
I think it would be a good idea to just use one package for consistency, but have no strong feelings.

**Comment by ksterne** [comment]
Thanks @asreimer for getting the logging added into the `rcParams` dictionary.  I started doing a little bit more on `radDataTypes.py` but I haven't finished it just yet.  

I feel the same as @aburrell where one package would be better.

Also, is the idea with the logging to continue to have printouts or should the messages be stored into a log file?  If so, do we need to add `filename=mylog.txt` to the `logging.basicConfig()` call?

**Comment by aburrell** [comment]
Perhaps have it default to STDOUT and add an option for an output file?  Either include a description of how to set this with logging or make a little wrapping routine.

**Comment by ksterne** [comment]
How do we want to handle tests of code?  I know we're eventually looking at unit tests in #178, but for now what do we want to do?  In particular, I'm looking at the `radDataTypes.py` code and the `if __name__=="__main__"` section has a lot of print statements to show that the code is working correctly.  I'm guessing these should be changed to `.info?  That will mean the user would need to change to 'debug' verbosity to see these outputs.

Revisiting the levels, I need to go back and set a few of the .infos to .debug.  I'll work on that now.

**Comment by cmeeren** [comment]
@ksterne I don't think that's what logging should be used for. The way I see it, when running tests, you want things to be printed to the console, not logged to a file.

In general, the goal of implementing logging should not necessarily be to replace each and every print statement. There are times when prints are the right thing. If you google "python print vs logging" I'm sure you'll get some best practices.

**Comment by asreimer** [comment]
I agree with @cmeeren on this. Leave the `if __name__ == "__main__":` stuff alone since it won't ever be run by any users and we are going to probably remove most of it later on anyway.

**Comment by ksterne** [comment]
Just finished off fan.py.  Does this look good for the docstring conversion?  I tried to do my best looking online as well as some files that had already been done here.

**Comment by aburrell** [comment]
@asreimer and everyone else,

I was working on dbUtils.py when I came across a call to a dictionary I can't find being defined anywhere.  It's 'refArr' on line 291.  There are a few other things in this routine that need more than formatting fixing as well (eg unused variables, missing optional input parameters).  This seems outside the scope of this pull request, but I'm not sure this routine will work if I don't fix them.  What's the procedure for this kind of thing?

**Comment by ksterne** [comment]
Hey @aburrell,

I found a similar thing where a unit test wasn't running for a file I was editting.  I just put that up as a new issue so that it's on our to-do list for the next release.

Also, @asreimer and others, is anyone else going to do the edits that @asreimer outlined for this pull request besides myself and @aburrell?  If it's just the two of us working on making the logging and numpy docstring conversions...it's going to take a while to get this new release out....

**Comment by asreimer** [comment]
Hey everyone, I've been a bit AFK finishing a paper (time to submit it wooo!), but I'll have more time in the next couple weeks to develop again. @aburrell and @ksterne have really been doing the majority of the heavy lifting on this. @cmeeren @MuhammadVT, are you two able to work on this at all? Even just 1 or 2 files would be helpful!

As for the of dbUtils, I'm not sure what to do about that exactly. I'm leaning towards simply making the docstring and logging edits for now and filing a bug report about it. It could take some time to unwind what we should do to "fix" and that could delay this already delayed 0.5-release. Does that sound reasonable?

**Comment by cmeeren** [comment]
@asreimer I'd like to but long story short, I'm totally swamped for the foreseeable future (at least a month).

**Comment by MuhammadVT** [comment]
Sorry everyone, I should have worked on the 0.5-release together with
@aburrell <https://github.com/aburrell> and @ksterne
<https://github.com/ksterne> before I was pushed to do so. I will start
working on it.
I have created a spreadsheet to know each developer's working status.
Please report your finished or ongoing work in this google spreadsheet
<https://docs.google.com/spreadsheets/d/139Lyb_I4_HAG9eQQDl24ei5MAGb8tMR_FHFYxlIXYDY/edit?usp=sharing>
.

**Comment by aburrell** [comment]
I’m working on the files in the sdio directory.  Feel free to take on anything else!

**Comment by ksterne** [comment]
Hello all, just finished off conversion for all the files in the pydarn/plotting/ directory.  Someone may want to give these files a second look to make sure I didn't miss something.  I'll see if I can find another  set of files to start tackling early next week.

**Comment by MuhammadVT** [comment]
Hi Kevin, I will look through it after I finish pydarn/radar/ directory in
two days.

**Comment by MuhammadVT** [comment]
Hi all,

I have finished the conversion for the files in pydarn/radar, Can anyone
take a look?

Thanks

**Comment by ksterne** [comment]
Hey @MuhammadVT,

Some of this is may be more style as I'm kind of new to this, but maybe it's worth making things consistent.  One thing that seems to be missing is the top coding line.  

For the `__init__.py`, I think the module section looks better like how @asreimer did it in the `pydarn/__init__.py` file.  I copied this for the one in plotting.  

One thing that the Numpy docstring website mentions that I picked up on is that either the class or the `def __init__` should be documented, but not both...or maybe not mixing the two.  I took to documenting the class and I think I've seen @aburrell has done the same.  I see this on the updateRadars that both are documented.

Otherwise, it would be good it we could keep track of optional and required parameters.  This is done a little strange in numpy where it's parametername : Optional[str].  Can you mark these?

To all, I certainly would like to hear anything about the pydarn/plotting/ files as far as docstring.  Anyone see anything?

**Comment by ksterne** [comment]
Hello all,

In doing the numpy docstring conversion, I've also found this website to be fairly helpful:
https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt

**Comment by MuhammadVT** [comment]
Hey @ksterne <https://github.com/ksterne>,

I have looked through all the files in pydarn/plotting directory for
docstring conversion and logging. Overall, they all look good. Here are
some minor issues I have noticed:

1. The module section in acfPlot.py and those in the rest of the files do
not seem to be consistent to me.
2. You seem to be mixing attributes with parameters in the class
level documentation in class MapConv in plotMapGrd.py, . Atributes like
map_obj, pcoll in musicFan and cbar_info in class musicRTI in musicPlot.py are
not documented.

I have corrected some obvious and minor things wherever necessary and made
a commit for that.

By the way, all the files do not fully comply with PEP8.

Thanks

**Comment by ksterne** [comment]
Hey @MuhammadVT,

Thanks for the comments here and really going through things.  Some of this was not knowing coding as well as I should and some of it is the fact that I took the existing docstrings and converted the style of them.  I agree, where we can, we should check these for content and make sure they are up to date.  I've just pushed up a commit here.  

Also, since PEP8 is not included in this pull request, I suggest we leave that beast for another day.  Focus should be on logging module use and numpy docstring conversion as this pull request has already been up for too long.

**Comment by ksterne** [comment]
Hi all,

I've finished off the davitpy/utils/ directory for numpy docstring conversion as well as implementing logging.  If anyone wants to give it a look over and comment on it, that would be great! 

Otherwise, I'll move on to another directory.

This is certainly taking much longer than anticipated!

**Comment by ksterne** [comment]
Hey @aburrell,

Why is the fitFilter function now greatly changed?  I see the previous version of this file is:

https://github.com/vtsuperdarn/davitpy/blob/6a3a51bbaf2e38c034167a61ca2b48adb509d052/davitpy/pydarn/sdio/fitexfilter.py

Which at line 130, fitFilter has four arguments.  But in your version, fitFilter now has way more arguments, of which two are duplicated and breaking the setup.py install command.  I also got an indentation error on the class Gate __init__ function.  I've pushed that fix on up.

Can you explain why the fitFilter now has greatly changed?  This seems like it's outside of the this pull request of converting docstrings and print->logging.

**Comment by aburrell** [comment]
It’s greatly changed because the file you could load was hardwired in to be “bks” at a particular time.  I didn’t think that was going to be of any use to anyone, so I changed it.  Feel free to revert to the previous version if you think I’ve overstepped.

**Comment by ksterne** [comment]
Hey @aburrell,

Ah, I can see where there's a problem there!  It did always open up Blackstone data.  I agree that this is something that we will need to change in the future, but I would like to keep the focus on what we want to do for this pull request and then fix other issues later on.  I can understand where we're now going through each of these files and really taking a look at them and finding all sorts of problems.  But I think a better way here is to note this down as an issue and stick to the numpy docstring and logging conversion.

The file otherwise really looks spectacular!  You've done a very good job so I don't want to revert to a previous version.  Would it be easy enough for you to change the function calls, docstring, and setting the inp variable back to what they were previously?  Even if it means hardcoding 'bks' in.  Then you can start an issue and reference that as a known problem.  You could keep a copy of that file around somewhere so that when we unfreeze pull requests to develop, you can copy and paste things back in and won't have lost your work here.  

Does that sound reasonable?  I'd like for us to keep focused on the two tasks that are left on this pull request.  Especially since it seems as though there's only three of us working on it and a new release pull request should not take this long.

**Comment by aburrell** [comment]
Hi Kevin,

I can make the changes tomorrow or Monday.  I’ve not had any luck saving old work and incorporating it later, but will give it another go.

**Comment by MuhammadVT** [comment]
Hey @ksterne <https://github.com/ksterne>,

I have looked through them for docstring conversion and and logging,  and
made some small corrections. But, again, I personally think that the module
section still does not seem to be complying with the numpy
docstring guideline.

Thanks.

**Comment by ksterne** [comment]
Hello all,

I've finished off the davitpy/gme/sat/ directory if anyone wants to give it a look.  Otherwise, I'll move onto `gme/plotting/`.

**Comment by MuhammadVT** [comment]
Hey @ksterne <https://github.com/ksterne>,

I have looked through the files in /gme/sat,  and made some small
corrections.

**Comment by ksterne** [comment]
Thanks for looking over things @MuhammadVT.  Seems as though I missed a few things here or there.

I've also finished off the other directories of:
`gme/plotting/`
`gme/isr/`
`gme/ind/`

**Comment by ksterne** [comment]
As a follow up here, I've also finished off:
`gme/base/`

So everything in `davitpy/gme/` should be ready to go.

**Comment by MuhammadVT** [comment]
Ok, I will look through them by Monday.

**Comment by aburrell** [comment]
I'm done going through sdio.  Someone else should take a look, there are bound to be some inconsistencies.  There's also a segment of the grid/map documentation that needs more variables described.  I haven't used those files yet so I don't know what all of them are.

**Comment by MuhammadVT** [comment]
Hey Kevin,

I have looked through all the folders under /davitpy/gme except for
gme/ind. I am seeing a systematic indentation problem in all the files
under gme/ind/.  Would you take a look them again?

Thanks

**Comment by ksterne** [comment]
Hey @MuhammadVT,

Thanks for pointing that out.  I fixed this in a few files, but must not have been good on checking it for every file.  I did a few manually before figuring out how to do it with a few commands with vi.  I noticed also that the files in the `gme/sat/` directory are tabbed with 2 spaces instead of 4.  Since this is outside of the requirements for this pull request, I think that should be left for another time.

I have fixed the tabs and spaces issue with my last commit.

**Comment by MuhammadVT** [comment]
Hey Kevin,

I have looked through /gme/ind as well. /gme can be considered as finished
in terms of docstring conversion and logging.

Thank you

**Comment by ksterne** [comment]
Hello all,

I've finished off the `.py` files in `davitpy/models/`.  If someone could review those that would be great.  

We're also getting *very* close to finishing off things here.  In `davitpy/` the `gme`, `utils` and now `models` directories have been finished.  This leaves the `pydarn` directory left.  However, within `pydarn`, the `dmapio`, `plotting`, `radar`, and `sdio` have been finished off.  This leaves `proc` left to complete.  Within that directory, I believe @MuhammadVT is working on the `signal` directory, leaving `fov` and `music`.  

Does anyone see anything else that I've missed?  I can started to work on those, but if someone else gets to it sooner then go for it!  We need to get this pull request done since, as I see it, we're several months behind!!!

**Comment by aburrell** [comment]
I think between the two of us we got the fov done.  Only music is left?

**Comment by ksterne** [comment]
Hey @aburrell,

Thanks for cleaning that up.  I saw the logging variables in there but since I didn't know that much about the code, I figured I would leave them alone.

That's right, only music left...I think.  I've made a start on it but need to get some other work done for today.

**Comment by ksterne** [comment]
Hello all,

I've just finished off the `proc/music.py` file for logging and numpy docstring conversion.  

It looks like there are still 3 files in `proc/signal/` that need to be converted.  @MuhammadVT are you working on these?

Otherwise, I can't find any other files that we need to convert.  Can anyone else see files that are still left to be done? 

So close!  Thanks for the hard work @aburrell and @MuhammadVT!

**Comment by MuhammadVT** [comment]
Hi All,

I have finished off the files in /proc/signal. Can anyone take a look?

I will finish reviewing davitpy/models/ and proc/music.py by tonight.

Thank you @ksterne <https://github.com/ksterne> and @aburrell
<https://github.com/aburrell> for doing most of the work.

**Comment by ksterne** [comment]
Hey @MuhammadVT,

The proc directory looks good, there were two files where the **kwargs notation was missed but I added that.  Also added in some parameters in one place where it seems as though they might have changed since it was originally documented.

**Comment by MuhammadVT** [comment]
Thank you @ksterne <https://github.com/ksterne> for reviewing them.

I have just finished reviewing davitpy/models/ and proc/music.py and made
some corrections on them.

**Comment by ksterne** [comment]
Hello all,

Since I think we've completed things as @asreimer outlined with this pull request, I think we should let this branch be tested for some time and then merge it into the master (after other things have happened of course).  I propose that merge the 0.5 release into master on March 14th, 2016 17:00 UTC.  Does anyone have any objections to this?

@asreimer would you like to do the merging on this?  If not, I can handle it.

**Comment by asreimer** [comment]
Oooo PI day. I'm ok with that merge date. I'll try to test this a bunch over the next week. 

Nice work @aburrell, @ksterne, and @MuhammadVT. This is some fantastic work you guys did.

**Comment by asreimer** [comment]
FYI just finishing up the testing. I've gone through all the `if __name__ == "__main__":` testing that exists and everything seems to be working there after I've fixed a few things. When removing brackets around logic in conditionals, we have to be careful. I found something that broke sdDataTypes. I also noticed a bug in `plotUtils.py` to do with the `mapObj`. 

I'm now perusing the code line by line to look for any other issues. This will take some time.

**Comment by ksterne** [comment]
Sounds good on the small edits you found @asreimer.  Good luck perusing through the code...but remember to keep on track for the Pi day deadline!

**Comment by asreimer** [comment]
Will do. This would be soooooo much easier if I had finished those unit tests that I was making. For the next release I think we should make it a top priority to incorporate unit testing. Simply run a test script and it tells you if any of the code is broken (assuming your unit tests are good).

**Comment by asreimer** [comment]
I've gone through the plotting and file reading code line-by-line (most used/important IMO). I only noticed one thing that we should probably change in the future (unless someone disagrees and thinks we should fix this now):

1) Consistent usage of logging with asserts. Sometimes asserts output to a logging statement, other times they don't. 

This is related to making sure we are consistent in our usage of logging.error, .info, etc. I think we did well there though :)

Nice work everyone! I'll make the release in the morning.

**Comment by asreimer** [comment]
Huh. Github has added "reactions" to comments on here now...

**Pull request merged**
