### PR TITLE
Minor Bugfix: ftype key in remote_dict and local_dict static through iteration

### PR DESCRIPTION
**Pull request by asreimer**
The ftype key in the `remote_dict` and `local_dict` was remaining static even though the code was iterating through the `arr` list (e.g. `arr = ['fitex','fitacf','lmfit']`). The consequence was that if no `fitex` files were found then `radDataOpen` or `sdDataOpen` would appear to be looking for `fitacf` and `lmfit` files next, but `ftype` in `remote_dict` or `local_dict` would still be set to `fitex`.

To see for yourself, you will need to add a print statement in `radDataOpen` or `sdDataOpen` after line 312 (https://github.com/vtsuperdarn/davitpy/blob/develop/pydarn/sdio/radDataTypes.py#L312) or after line 261 (https://github.com/vtsuperdarn/davitpy/blob/develop/pydarn/sdio/sdDataTypes.py#L261). Look for a file that can't yet exist, for example, something from the future.

This is a very simple and minor bugfix. (edit: Ha haha hahahaha ya right...)

### CODE REVIEW

**Comment by MuhammadVT** [comment]
I confirm that when looking for a file from future time using the current
radDataType.py and sdDataType.py codes in develop branch, ftype in
remote_dict or local_dict takes the first element in the arr list and
remains static with that value while the code was iterating through
the arr list.
I have also tested the code in this pull request, and it does update ftype
 in remote_dict or local_dict correctly.

**Comment by ksterne** [comment]
After a bit of help from @MuhammadVT, I started testing this a little bit here.  I can confirm that after making the changes to the code that you noted, that ftype in the remote_dict is updating and iterating through fitex, fitacf, and lmfit if I don't give it a ftype to look for.

However, I don't see it iterating through the ftype for the local_dict.  It seems as though if it cannot find a file locally from the first go of things that it gives up and tries going through the remote protocols.  Should this happen this way?  Or should we expect it to first cycle through the file types locally and then go through the file types remotely.  That may be a bigger question than what this pull request is addressing...or maybe I'm not in the right scenario to test the ftype iterating in local_dict.

**Comment by asreimer** [comment]
Hmm I see the same thing... I'll figure out what is going on here and report back.

**Comment by asreimer** [comment]
Meant to post here earlier. @ksterne, the behaviour that you found is due to another subtle bug that might as well be fixed in this pull request too. I've detailed the bug here: https://github.com/vtsuperdarn/davitpy/issues/129.

I'm working on a fix.

**Comment by asreimer** [comment]
Ok. Everything seems to be working now. The latest commits should resolve this bug and the bug detailed in #129. I should change the title of this pull request from "Minor Bugfix" to "Cascading serious of bugfixes"... There were a few things like missing `try:  except:`s that would cause fetchUtils to violently give up and the exception would get caught by `radDataOpen` instead and very strange behaviour would occur, so I fixed that too. Another thing I found was that if no files were found, fetchUtils would search back in time until an error was thrown at the year 1899, so I added an optional arguement called back_time that limits how far back fetchUtils will search. Default is 1 year; performance is still very good with this set to 1 year.

There are 8 tests that you should run to validate this pull request, in addition to the testing discussed at the top of this pull request:

__Verify that:__
1) `myPtr = pydarn.sdio.radDataOpen(datetime(2015,3,1),'sas',eTime=datetime(2015,3,1,3,30),fileType='fitacf')` does not successfully find data. Note also that the iteration over various filetypes is working!

2) `myPtr = pydarn.sdio.radDataOpen(datetime(2014,3,1),'sas',eTime=datetime(2014,3,1,3,30),fileType='fitacf',local_fnamefmt=['{date}.{hour}{min}....{radar}.{ftype}'])` successfully grabs 3 files from a local source that have data for the specified `sTime` and `eTime`.

3) `myPtr = pydarn.sdio.radDataOpen(datetime(2014,3,1),'sas',eTime=datetime(2014,3,1,3,30),fileType='fitacf',remote_fnamefmt=['{date}.{hour}{min}....{radar}.{ftype}'],src='sftp')` successfully grabs 3 files from a remote source that have data for the specified `sTime` and `eTime`.

4) `myPtr = pydarn.sdio.sdDataOpen(datetime(2015,3,1),eTime=datetime(2015,3,1,3,30),fileType='map')` does not successfully find data.

5) `myPtr = pydarn.sdio.sdDataOpen(datetime(2014,3,1),eTime=datetime(2014,3,1,3,30),fileType='map')` successfully grabs 1 file, but the file type is mapex instead of map.

6) `myPtr = pydarn.sdio.sdDataOpen(datetime(2014,3,1),eTime=datetime(2014,3,1,3,30),fileType='map',src='sftp')` successfully grabs 1 files from a remote source, but the file type is mapex instead of map.

7) execute `python radDataTypes.py` and checkout output for errors

8) execute `python sdDataTypes.py` and checkout output for errors

**Comment by MuhammadVT** [comment]
Hi all,

Here are the testing results I got:

1) Working as expected, doesn't find data but various filetypes are
iterating correctly for both local and remote cases.

2) Working as expected, grabs 3 files from local source.

3) Working as expected, grabs 3 files from remote source.

4) Working as expected, couldn't find data.

5) Working as expected, doesn't find map file locally, but grabs one mapex
file from remote server.

6) Working as expected, directly searches for a map file from a remote
server. It doesn't find map file locally, but grabs one mapex file from
remote server.

7) executing python radDataTypes.py gives no errors except for  "Error:
Cached dmap file has unexpected md5sum".

8) executing python sdDataTypes.py gives no errors except for "Error:
Cached dmap file has unexpected md5sum".

**Comment by mrwessel** [comment]
Tests 1-3 and 6 work properly.

Test 4 produces an error: `local variable 'temp' referenced before assignment`, and refuses to try reading local data (it goes direct to SFTP, and fails to find data there).

Test 5 produces the same error, then successfully finds data over SFTP.

Test 7 produces the Md5sum error seen by @MuhammadVT and otherwise works correctly.

Test 8 finds files for 20120710 and 11 over SFTP, then removes the 11 file as invalid.  The resulting file size is 15330198 (too small) and the Md5sum is incorrect, as seen by @MuhammadVT.  The rest of the remote test works.  The local test fails again on the same 'temp' error as tests 4 and 5, then successfully attempts remote.

Hmm, this could be important:  in both of the `__name__==__main__` tests the attempt to find local files gets the cached files from the preceding remote fetches instead of *actually* looking at local.  This is tangentially related to #130.

**Comment by asreimer** [comment]
Oh man. I should stop with the pull requests at 2am...

@mrwessel, the bug you are seeing on test 4 is due to a copypasta error that I made in `sdDataTypes.py`. I'll let you fix this in a pull request to my branch as you have indicated in private communication.

**Comment by mrwessel** [comment]
The map/ex errors (in sdDataTypes) are fixed in pull request number 1 on the @asreimer fork (see above for link).  The tests for map/ex now work properly, but there are still problems with test 7.

**Comment by mrwessel** [comment]
Details of test 7

First test:  "Running sftp grab example for radDataPtr"
Works as expected.

Second test:  "Running local grab example for radDataPtr"
Checks file `/tmp/sd/20121101.C0.fhe.fitacf`, which is different from the cached file made out of the 0000.03, 0201.00, and 0401.00 files in the first test.  Result is wrong file size and wrong Md5sum.

Third test:  "Running sftp grab example for testint the channel option for channel c"
Works as expected.

Fourth test:  "Running sftp grab example for testing the channel option for all"
File size is correct but Md5sum is wrong.

**Comment by asreimer** [comment]
Alright, I have implemented @mrwessel changes and fixed the issues found by @MuhammadVT. Test 7 failed because the code never used to sort the fit files before concatenating them. So now that it does, the file size is the same, but the md5sum is different.

When I run tests 1-8 I don't receive any errors/unexpected results.

Could both of you (@mrwessel and @MuhammadVT ) run tests 1-8 again to verify? Anyone lurking in the shadows is welcome to test too!

**Comment by MuhammadVT** [comment]
Checked 1-8 again with various time arguments, working nicely on my side.

By the way, sorry for no being able to catching the error messages that
Matt has noticed in test 4 and 5.

**Comment by asreimer** [comment]
Hey eveyone, can I get this merged in? @MuhammadVT tested this and found that it passed the tests. I really want to get the rc_params thing merged in but would rather some of these other "dangling" pull requests get cleaned up too. Thanks!

**Comment by aburrell** [comment]
@asreimer,

I was about to merge this, but I found I was downloading 2 files instead of 3.  I think this is a difference between my environment variables and yours, but when I tried to use time_inc to get the same results as you, I found that this input had been removed.

Is there a good reason for this?  I've needed to use time_inc to load daily fitacf files before and I think it's a mistake to remove this option from the keyword arguments.

**Comment by asreimer** [comment]
Hey @aburrel, thanks for working on this stuff!

What server are you using for testing? I'm assuming that people are using
the VT server in the test cases that I provided. If you don't use VT then
I'm not sure the number of files that you will fetch.

As for time_inc, this was purposefully removed. No one stores all of their
files in a completely consistent time increment format so having time_inc
is kind of useless. Instead we've (@mrwessel and I) worked out a way to
fetch files in a more general way that doesn't need time_inc.

FYI, I'm not at my computer until this weekend, but I can try to answer
questions on my phone.

**Comment by aburrell** [comment]
@asreimer 

No prob, hopefully the questions won't be too hard.

So, I tested this fetch on the files that I needed to change time_inc for previously, and it worked fine.  So, I'm onboard for that change now.

I am having problems grabbing the map files though.  I'm attempting to use the VT database and get this error:

[Errno 8] nodename nor servname provided, or not known

However, when I sftp into the server, I have no problem finding the data.  Here's the command I'm using:

rad  = 'sas'
stime = dt.datetime(2014, 3, 1)
etime = dt.datetime(2014, 3, 1,3,30)
rad_ptr = sdio.sdDataOpen(stime, rad, eTime=etime, fileType="map",remote_dirfmt='/data/{year}/{ftype}/{hemi}/', remote_site='sd-data2.ece.vt.edu', username='sd_dbread', password='5d')

Any ideas as to the problem?

Cheers,
Angeline

**Comment by asreimer** [comment]
Whew! That's a relief :-)

Try using sd-data.ece.vt.edu instead of the sd-data2? I'll test some stuff
soon if that doesn't work. Might have to talk to @ksterne about the VT
hostnames.

**Comment by aburrell** [comment]
Same problem :(  It looks like it’s trying to use environment variables instead of the directed input.  Here’s the entire error report:

In [30]: rad_ptr = sdio.sdDataOpen(stime, rad, eTime=etime, fileType="map",remote_dirfmt='/data/{year}/{ftype}/{radar}/', remote_site='sd-data.ece.vt.edu', username='sd_dbread', password='5d')

Looking locally for map files with hemi: sas
Environment variable DAVIT_SD_LOCAL_DIRFORMAT not set, using default: /sd-data/{year}/{ftype}/{hemi}/
Environment variable DAVIT_SD_LOCAL_FNAMEFMT not set, using default: ['{date}.{hemi}.{ftype}']
could not find map data in local files

Looking locally for mapex files with hemi: sas
could not find mapex data in local files

Looking on the remote SFTP server for map files
Environment variable DAVIT_SD_REMOTE_FNAMEFMT not set, using default: ['{date}.{hemi}.{ftype}']
Environment variable DB_PORT not set, using default: 22
'radar'
problem reading from sftp server

Looking on the remote SFTP server for mapex files
'radar'
problem reading from sftp server

Sorry, we could not find any data for you :(

**Comment by asreimer** [comment]
Hey @aburrell,

I found the problem and unfortunately it's a user error :) The command you used:
`rad_ptr = sdio.sdDataOpen(stime, rad, eTime=etime, fileType="map",remote_dirfmt='/data/{year}/{ftype}/{radar}/', remote_site='sd-data.ece.vt.edu', username='sd_dbread', password='5d')`

is not the correct syntax for getting map files. Have a look at the documentation on sdDataOpen and you'll see what I mean. For convenience, the proper syntax would have been:
`rad_ptr = sdio.sdDataOpen(stime, eTime=etime, fileType="map",remote_dirfmt='/data/{year}/{ftype}/{hemi}/'', remote_site='sd-data.ece.vt.edu', username='sd_dbread', password='5d')`

**Comment by asreimer** [comment]
On that note, we still need to add input sanitization to many of the functions in davitpy.

**Pull request merged**
