### PR TITLE
enhancement_rc_params

### PR DESCRIPTION
**Pull request by asreimer**
This is it, finally. The big pull request that changes the directory structure of davitpy and how it is imported (ie. more like matplotlib now, where one must use `from davitpy import pydarn` instead of `import pydarn`. Also, a davitpyrc file is now needed instead of using environment variables to set things like the `DAVIT_SD_REMOTE_DIRFORMAT`, `DB`, etc.

To test this pull request, I suggest testing *EVERYTHING*. I wouldn't be surprised if there are a few issues that I've missed since this pull request affects almost all of the code.

I'll post my test results once I've completed them.

### CODE REVIEW

**Comment by asreimer** [comment]
Forgot to mention that I've included all of the commits that @w2naf had in his pull request (#135) as well.

**Comment by w2naf** [comment]
Thank you, @asreimer !  I will be making a lot of plots over the next few days/weeks, so I will be dogfooding this.

**Comment by w2naf** [comment]
Hi, @asreimer.  I changed around the README.md a bit and added some comments to the davitpyrc file.  Comments and questions:

1. Can we get rid of test.py in the root directory?
2. Is the profile.bash useful at all any more?
3. I think we should get rid of custom binaries/scripts like 'davitpy-notebook' and instead have people just use the standard 'ipython' and 'ipython notebook'.  If we do that, it will reduce one more thing that we need profile.bash for.
4. I think we should get rid of davitpyrc.template.  I don't like having the same thing in more than one place because it leads to confusion.  Instead, I talk about davitpyrc up front in the README.

Best,
Nathaniel

**Comment by asreimer** [comment]
Hey @w2naf, that sounds excellent! I just added an dependency install script for openSUSE (that's how I got davitpy to install on the machine I'm currently on).

To address your comments/questions:
1) Yes. I've done that now.
2) The profile.bash script is needed if we want to install a `davitpy`, `davitpy-notebook`, etc. executables. *I think* is is also needed to specify the AACGM tables location, but I've almost got that fixed up so we don't need it for that. 
3) This is related to 2) a little, and I agree. We should definitely get rid of `davitpy`, `davitpy-notebook`, etc, but have instructions available for people to be able to create their own ipython profiles.
4) I'm ok with removing the davitpyrc.template. I'll do that and review the stuff you added to the README.

I'll be working on these things and testing this pull request today.

**Comment by w2naf** [comment]
Hi again, @asreimer .  So it turns out that iPython, the notebook, and other modules that were part of iPython are splitting (http://blog.jupyter.org/2015/04/15/the-big-split/).  I'm finding out that this means that once you update a system and re-run our dependencies script, the notebooks don't work.

Unfortunately, they don't yet have it set up so you can simply run "pip install notebook".  They say it is coming.  In the mean time, I'm trying to figure out how to get notebooks to run on my machine again.

We will also need to know how to make our install scripts work in this situation.

~Nathaniel

**Comment by asreimer** [comment]
Hmmm, that kind of sucks. Hopefully they can get the stable releases out soon!

**Comment by w2naf** [comment]
It is frustrating…  I now can’t get my notebooks to run properly.

So far, I’ve had to update:

sudo pip install --upgrade pycurl
sudo pip install --upgrade jsonschema
sudo apt-get install npm

Before running the instructions on https://github.com/jupyter/notebook <https://github.com/jupyter/notebook>.  Even once I got it to run, it can’t find the CSS files.

Part of it could be that I’m running it on an Ubuntu 12.04 machine.  I guess I’ll come back to it later.

~Nathaniel

**Comment by w2naf** [comment]
Hello, again.  I have my notebook situation resolved for now.  I think the problem is that we have the `--upgrade`` flag on all of the pip commands in the debian_dependencies.sh script.  When I ran the script yesterday, it upgrade my ipython to 4.0.0-dev, which is split from the notebook project.  I then tried installing the new notebook from https://github.com/jupyter/notebook, which failed.  I opened /jupyter/notebook#225, where I was told to go back to a stable version.  I did that by uninstalling all of ipython, and then running a simple `sudo pip install ipython`.  Everything works again :-).  The moral of this saga is that we need to figure out how to make the dependency installation scripts not break things.

Best,
Nathaniel

**Comment by w2naf** [comment]
Hello, yet again!  I have another issue. Does this branch change how errors like divide by zero are being handled?  I went to run the MUSIC.ipydb notebook, and I now have an error that does not appear in #134.

I run:
```dataObj     = pydarn.proc.music.musicArray(myPtr,fovModel='GS')```

And get this error:
```
/usr/local/lib/python2.7/dist-packages/davitpy-0.2-py2.7-linux-x86_64.egg/davitpy/pydarn/radar/radFov.py:473: RuntimeWarning: divide by zero encountered in double_scalars
  slantRange**2)/(2. * (tRe+tAlt) * slantRange)))
```

Traceback:
```
/usr/local/lib/python2.7/dist-packages/davitpy-0.2-py2.7-linux-x86_64.egg/davitpy/pydarn/radar/radFov.pyc in calcFieldPnt(tGeoLat, tGeoLon, tAlt, boreSight, boreOffset, slantRange, elevation, altitude, model, coords, fov_dir)
    471             # pointing elevation (spherical Earth value) [degree]
    472             tel = np.degrees(asin(((RePos+xAlt)**2 - (tRe+tAlt)**2 -
--> 473                                 slantRange**2)/(2. * (tRe+tAlt) * slantRange)))
    474 
    475             # estimate off-array-normal azimuth (because it varies slightly

ValueError: math domain error
```

This happens when slantRange is 0, which can occur in the GS mapping model.

**Comment by asreimer** [comment]
I never understood why we needed to run the pip commands with the upgrade flag, but I never formally questioned it. If it doesn't cause any issues and one is able to install and run DaViTpy, I am in favour of simply removing the upgrade flags.

That divide by zero error you found is actually the result of another error. It is caused by an indentation error on lines 327, 330 and 331 in radFov.py (compare with lines 222-225 of https://github.com/w2naf/davitpy/blob/enhancement_rc_params/davitpy/pydarn/radar/radFov.py). I think this happened with the PEP8 compliance edits @aburrell made when adding in the backFov stuff. I've fixed it now.

Bring on the bugs, I've got my hammer.

Also, I wanted to say that I've removed the need for the `AACGM_DAVITPY_DAT_PREFIX` environment variable in `profile.bash`. I've completely removed the other stuff in the `profile.bash` too, which means that we no longer install a davitpy executable or davitpy-notebook executable. For people who liked/would like this functionality, I've added a README.md file (work in progress) that will explain how to set up your ipython configuration to auto-import davitpy on startup, and how to install a 'davitpy' executable. 

Officially, 'profile.bash' is dead ("long-live profile.bash" eh @ajribeiro? :-)), also I've removed profile.mac!
Now we just need to figure out how to get aacgm/etc to compile on windows and davitpy can run on that too.

**Comment by w2naf** [comment]
Hi, @asreimer .

I originally put the `--upgrade` flags when I found out that nothing would get upgraded if I did not.  I think I ran into some problem that I would use apt-get to do a system update, and then that would break some python package that depended on some other system code that was now too new.  By doing it this way, it gave us a way of easily making sure our python packages were also always up to date.  It's worked pretty well until now that notebook has split from ipython, and the `--upgrade` gives us a version that doesn't work.

I think there is a way to define dependencies in setup.py.  Maybe we should do this as much as possible, and start recommending the use of pip for installation.  This moves us closer to a `pip install davitpy` paradigm.  This will also allow us to reduced the length of the dependency scripts, and should make it easier to install on any flavor of linux or Mac.  Any thoughts here?

I'm glad you have your hammer!  Thanks for fixing that one.  I fixed a couple more in mapOverlay.py.  I had a general `import numpy as np` in there that was removed.  I understand that we are trying to be selective about imports, but we use numpy so generally, I don't think it's worth being selective in this case.  Also, I fixed some `radFov` variables that were not changed over to `rad_fov`.

Great about eliminating profile.bash!  I see there is still a profile_usask.bash.  Can we get rid of that, too?  Also, who uses those executables?  I think we should just kill them.  It's not very pythonic to start things up that way.  People really just need to `import davitpy`.

Ok, that's all for now!

~Nathaniel

**Comment by bsinglet** [comment]
re: the use of pip --upgrade,

In installing davitpy on Fedora 21, the --upgrade flag was necessary to
keep the Python packages compatible with the other software installed along
the way.  As Nathaniel said, though, that could be fixed with explicitly
requiring a certain version of each package.

As a side note, if anyone wants my Fedora install script, I can commit it
to my branch tonight.  For the most part, I only had to replace 'apt-get'
with 'dnf' (Fedora's new package manager that replaces yum), although there
were some packages that were named differently on Fedora, and some
additional dependencies that aren't needed on Ubuntu but are here.

-Benjamin Singleton

**Comment by asreimer** [comment]
Hey @bsinglet,

If you could commit your script that would be great.

I also agree that we should move towards specifying dependencies
explicitly. I think that can be done in the setup.py file.

Cheers

**Comment by bsinglet** [comment]
Hey @asreimer,

No problem at all.  My script is on my personal computer, so I can't commit
it until I get out of work, but I'll have it up tonight.

Another thing that was necessary for me to install was to delete the
fortran .mod files and recompile them with my version of gfortran, as they
aren't compatible across different versions.  We should either require a
specific version of gfortran across all users, or automate the production
of .mod files at install time.

-Benjamin

**Comment by asreimer** [comment]
Ya that's a problem in the master branch. I'm happy to report that the next
release of master will have those files removed (they are no longer in the
develop branch). We have also removed the mastermake script (thankfully) as
everything is now handled by the setup.py file.

**Comment by w2naf** [comment]
Hey, guys.  Right now we are still calling the DAVITPY envvar in some fortran subrouties, a la https://github.com/vtsuperdarn/davitpy/blob/6e0d866a3668669f86dee4f969cd4c73226581bb/davitpy/models/iri/irisub.for#L364-L365 .

Do you know an appropriate way to fix this with the rc model?

Thanks,
Nathaniel

**Comment by asreimer** [comment]
Hey @w2naf, I've an idea, but I'm not sure how to do it in fortran. Basically have a look at what I did to aacgm in the aacgmlib.c file, specifically here (https://github.com/vtsuperdarn/davitpy/blob/enhancement_rc_params/davitpy/models/aacgm/aacgmlib.c#L26) where I added a variable that is passed to aacgm (in_coeff_prefix). This variable is used to specify the file path instead of using the old environment variable AACGM_DAVITPY_DAT_PREFIX. Then, I added some code to the aacgm `__init__.py` file (https://github.com/vtsuperdarn/davitpy/blob/enhancement_rc_params/davitpy/models/aacgm/__init__.py#L22) so that the default file path would be one specified by rcParams but able to be changed by the user also. You'll notice to accomplish this I renames the aacgmConv and aacgmConvArr functions in the aacgmlib.c file and "masked" them within the python define aacgmConv and aacgmConvArr. Clear as mud?

So that's what I propose doing, but I'm not sure how to accomplish it in fortran. Of course you'll need to add a default 'DAVITPY' entry into the rcParams dictionary (in rcsetup.py here: https://github.com/vtsuperdarn/davitpy/blob/enhancement_rc_params/davitpy/rcsetup.py#L194). Have a look at how I obtained aacgm_coeffs_dir (https://github.com/vtsuperdarn/davitpy/blob/enhancement_rc_params/davitpy/rcsetup.py#L186) to get the "/davitpy/models/iri" path that you need.

**Comment by w2naf** [comment]
Thanks, @asreimer .  I'll have to think about that for a bit.  For the moment, I've just added back an environment variable on my personal computer to do the runs I need for my paper.

I've also added all the .gitignores recommended by github for python repositories.

~Nathaniel

**Comment by asreimer** [comment]
Hey @w2naf, that issue with the IRI fortran code needing updating to use davitpy.rcParams happens in hwm07 also. I think you knew that, but I'm documenting it here. (https://github.com/vtsuperdarn/davitpy/blob/enhancement_rc_params/davitpy/models/hwm/hwm07e.f90#L580-L581)

**Comment by asreimer** [comment]
So I fixed the hwm model. I'm going to give IRI a try right now.

**Comment by w2naf** [comment]
Awesome! Thanks!

**Comment by asreimer** [comment]
Alright, so `iri` and `raydarn` have been modified so that they use `rcParams` instead of the `DAVITPY` environment variable. What a rabbit hole I fell down fixing this one up... But it is all working now! Well, I still need to create the proper function wrapper in the `iri` `__init__.py`, but otherwise all working. `raydarn` works like a charm.

I made a couple other changes too. For one, raydarn is now installed by default with the rest of davitpy (the setup.py file handles this in a windows friendly way!). I think we want this by default, yes? Raydarn could use a clean up too I think.

Also refactored the `setup.py` file a bit so it is easier to read.

**Comment by asreimer** [comment]
For anyone wanting to test `raydarn` out:

    from davitpy.models import raydarn
    rto = raydarn.RtRun(datetime(2012,11,18,5),rCode='bks', beam=12, nprocs=1)
    rto.readRays()
    ax, aax, cbax = rto.rays.plot(datetime(2012,11,18,5), step=10, showrefract=True, nr_lim=[.85,1])
    ax.grid()
    ax.figure.show()

Of course, make sure that `nprocs` in the `RtRun` call is no greater than the number of processors you have. The note in the rt.py file about this should maybe be a warning? "The ray tracing requires mpi to run. You can adjust the number of processors, but be wise about it and do not assign more than you have"

**Comment by w2naf** [comment]
Ashton, I owe you a beer for working this out!!!

Alas, a few issues.  I just tried running the notebook.  After running cell [4], `rto.readRays()`, we get:

```
----
error                                     Traceback (most recent call last)
<ipython-input-4-228962394d0d> in <module>()
      1 # Read rays into memory
----> 2 rto.readRays()

/home/w2naf/davitpy/davitpy/models/raydarn/rt.py in readRays(self, saveToAscii, debug)
    235         self.rays = Rays(fName, 
    236             site=self.site, radar=self.radar,
--> 237             saveToAscii=saveToAscii, debug=debug)
    238         # Remove Input file
    239 #        subp.call(['rm',fName])

/home/w2naf/davitpy/davitpy/models/raydarn/rt.py in __init__(self, readFrom, site, radar, saveToAscii, debug)
    818 
    819         # Read rays
--> 820         self.readRays(site=site, debug=debug)
    821 
    822         # If required, save to ascii

/home/w2naf/davitpy/davitpy/models/raydarn/rt.py in readRays(self, site, debug)
    843             if debug:
    844                 print self.readFrom+' header: '
--> 845             self.header = _readHeader(f, debug=debug)
    846             # Then read ray data, one ray at a time
    847             while True:

/home/w2naf/davitpy/davitpy/models/raydarn/rt.py in _readHeader(fObj, debug)
   1077         'hmf2', 'nmf2')
   1078     # Read header
-> 1079     header = OrderedDict( zip( params, unpack('3i9f3i5f', fObj.read(3*4 + 9*4 + 3*4 + 5*4)) ) )
   1080     header['fext'] = unpack('10s', fObj.read(10))[0].strip()
   1081     header['outdir'] = unpack('250s', fObj.read(250))[0].strip()

error: unpack requires a string argument of length 80
```

I think you probably need the same fix I applied the other day when I was extending the length of the allowable file paths.  Namely, I had to change the length of a MPI variable definition. See 38d9eba, where the last number of raytrace_mpi.f90 L286 needs to be the total number of string characters in the header, which in my case was 10 for the extension + 250 for the file path.  You probably need to add something here (or something similar) to account for the new variables you are passing.

Also, you won't necessarily catch errors or changes to your code unless you delete the temporary files (/tmp/*.dat and /tmp/rtrun_0.inp) between runs.  We should put something in that limits the chances of the user running off of stale files.  There used to be something implemented like that, but it wasn't done well.  That is because it was done in a way that deleted these cache files even if you wanted to reuse them.

Talk to you later,
Nathaniel

**Comment by w2naf** [comment]
Oh!  You can also see I made a small change to your raydarn makefile path in setup.py.  It was set to the absolute path on your machine; I changed it to a relative path.

~Nathaniel

**Comment by asreimer** [comment]
I was getting the same error as you, but it goes away when  `nprocs=1`. I only have 1 processor on my computer so I thought that I have to use `nprocs=1`. You were able to use `nprocs=4` before?

**Comment by asreimer** [comment]
Have a look at the file size of the `.dat` files. I'm seeing that they are all 0 unless I use `nprocs=1`. Maybe @sdelarquier can shed some light on what is happening here.

**Comment by salsrag** [comment]
Sebastien was fairly specific. He said that you should net set the numerous of processors to more than you have. 
Ray

Sent via the Samsung Galaxy S® 6, an AT&T 4G LTE smartphone fix. -------- Original message --------

**Comment by w2naf** [comment]
Hi, @asreimer .  Yes, things worked fine with the standard rayTracing notebook (https://github.com/vtsuperdarn/davitpy/blob/enhancement_rc_params/docs/notebook/rayTracing.ipynb) and nprocs=4 using the 38d9eba commit and a fresh /tmp directory.  I think you just need to modify those MPI declarations above.  That might explain why your code works fine with nprocs=1 vs nprocs=4.  Maybe with 1 processor, that declaration is not important.

I think @sdelarquier had suggested he wanted to re-write the ray tracer in python.  However, I think that is outside of the scope of this pull request.

~Nathaniel

**Comment by w2naf** [comment]
Hi, @salsrag!  I'm glad to see you are seeing this discussion.

The processor increase should simply serve to make things faster.  I haven't tried setting it to more than I have, but I would hope that regardless of what you have it set to, the code would still work.  You want it so that if you set it to a number of processors less than what is available, you simply see a reduction in speed (but possibly keeps resources free for other tasks).  If you set it to greater than what is available, you want it to use everything you have, but not break because it is trying to use something that is not there.

~Nathaniel

**Comment by salsrag** [comment]
My feeling is that there is overhead and resources asociated with setting up any process. So, if you try to set up more processes than you can handle efficiently you run into trouble. 


Sent via the Samsung Galaxy S® 6, an AT&T 4G LTE smartphone-------- Original message --------

**Comment by w2naf** [comment]
Hi, @asreimer !  It now works with nproc >1.  See the last commit for details.

See you later,
Nathaniel

**Comment by asreimer** [comment]
Hey that's excellent @w2naf! Teamwork FTW!

I'm hopefully going to finish pouring over the code today and then we can hopefully merge this soon! When we do, I'll have a unit testing feature branch that can be pulled in and should make all our lives so much easier while testing each other's new code.

**Comment by w2naf** [comment]
Fantastic!  One more thing we need to take care of (this is a warning out of the raytrace notebook, but applies in general to importing davitpy):

```
/home/w2naf/davitpy/davitpy/pydarn/plotting/plotMapGrd.py:51: SyntaxWarning: import * only allowed at module level
  def __init__(self, startTime, mObj,
/home/w2naf/davitpy/davitpy/pydarn/plotting/plotMapGrd.py:51: SyntaxWarning: import * only allowed at module level
  def __init__(self, startTime, mObj,
/home/w2naf/davitpy/davitpy/pydarn/plotting/plotMapGrd.py:51: SyntaxWarning: import * only allowed at module level
  def __init__(self, startTime, mObj,
/home/w2naf/davitpy/davitpy/pydarn/plotting/plotMapGrd.py:92: SyntaxWarning: import * only allowed at module level
  def overlayGridVel(self, pltColBar=True,
/home/w2naf/davitpy/davitpy/pydarn/plotting/plotMapGrd.py:542: SyntaxWarning: import * only allowed at module level
  def overlayMapModelVel(self, pltColBar=False,
/home/w2naf/davitpy/davitpy/pydarn/plotting/plotMapGrd.py:611: SyntaxWarning: import * only allowed at module level
  def overlayMapFitVel(self, pltColBar=True,
```

Basically, we need to go through plotMagGrd.py and be specific about imports.  I will probably get a chance to do it in the next few days, but if anyone else feels like tackling it first, be my guest!

~Nathaniel

**Comment by asreimer** [comment]
Yay! I fixed the tsyganenko bug (although I'm not sure how...). So #100 is resolved now. If you want to see a working tsyganenko, pull down this branch (or cherry pick commit d88bfae) and run the following code:

    from numpy import arange, zeros, ones
    from models import tsyganenko
    lats = arange(10, 90, 10)
    lons = zeros(len(lats))
    rhos = 6372.*ones(len(lats))
    trace = tsyganenko.tsygTrace(lats, lons, rhos,datetime=datetime(2014,9,17,12))
    ax = trace.plot()

and you should get this:
figure_1

**Comment by asreimer** [comment]
Alright, I'm done working on this pull request (unless someone finds a bug related to the purpose of this pull request). 

I have tested everything that I could (plotting, file fetching, etc.) and it's all working. There are some things that need to be changed in our plotting routines, especially the convection maps and the rti plotting, but those will have to be the topics of a future pull request.

Can we get someone to also do some testing and then get this thing merged in?

**Comment by w2naf** [comment]
Hi, @asreimer .  I started running through the notebooks, and found and fixed a few small bugs.  Here are some things that I found but have not yet fixed:

Cell 6 of geoPack.ipynb traceback:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-f214ec056775> in <module>()
      1 # Test gspToGcar (graphic)
      2 fig = plt.figure(figsize(10,10))
----> 3 ax = fig.add_subplot(111, projection='3d')
      4 ax.plot3D([0,Rav],[0,0],[0,0],'b')
      5 ax.plot3D([0,0],[0,Rav],[0,0],'g')

/usr/local/lib/python2.7/dist-packages/matplotlib/figure.pyc in add_subplot(self, *args, **kwargs)
    962                     self._axstack.remove(ax)
    963 
--> 964             a = subplot_class_factory(projection_class)(self, *args, **kwargs)
    965 
    966         self._axstack.add(key, a)

/usr/local/lib/python2.7/dist-packages/matplotlib/axes/_subplots.pyc in __init__(self, fig, *args, **kwargs)
     76 
     77         # _axes_class is set in the subplot_class_factory
---> 78         self._axes_class.__init__(self, fig, self.figbox, **kwargs)
     79 
     80     def __reduce__(self):

/usr/lib/pymodules/python2.7/mpl_toolkits/mplot3d/axes3d.pyc in __init__(self, fig, rect, *args, **kwargs)
     89         Axes.__init__(self, fig, rect,
     90                       frameon=True,
---> 91                       *args, **kwargs)
     92         # Disable drawing of axes by base class
     93         Axes.set_axis_off(self)

/usr/local/lib/python2.7/dist-packages/matplotlib/axes/_base.pyc in __init__(self, fig, rect, axisbg, frameon, sharex, sharey, label, xscale, yscale, **kwargs)
    435         self._hold = rcParams['axes.hold']
    436         self._connected = {}  # a dict from events to (id, func)
--> 437         self.cla()
    438         # funcs used to format x and y - fall back on major formatters
    439         self.fmt_xdata = None

/usr/lib/pymodules/python2.7/mpl_toolkits/mplot3d/axes3d.pyc in cla(self)
   1043         self._zmargin = 0
   1044 
-> 1045         Axes.cla(self)
   1046 
   1047         self.grid(rcParams['axes3d.grid'])

/usr/local/lib/python2.7/dist-packages/matplotlib/axes/_base.pyc in cla(self)
    906         self.containers = []
    907 
--> 908         self.grid(self._gridOn, which=rcParams['axes.grid.which'])
    909         props = font_manager.FontProperties(size=rcParams['axes.titlesize'],
    910                                         weight=rcParams['axes.titleweight'])

/usr/lib/pymodules/python2.7/mpl_toolkits/mplot3d/axes3d.pyc in grid(self, b, **kwargs)
   1254         if len(kwargs) :
   1255             b = True
-> 1256         self._draw_grid = maxes._string_to_bool(b)
   1257 
   1258     def ticklabel_format(self, **kwargs) :

AttributeError: 'module' object has no attribute '_string_to_bool'

<matplotlib.figure.Figure at 0x7fcbf9c1e190>
```

Also, running the IRI in models.ipynb causes the kernel to die.

I need to head to bed for now!

~Nathaniel

**Comment by w2naf** [comment]
I'm back!  I used git-bisect figured out that 2489f7e2108c9322f5030bc40376f5ef0f5781b6 breaks the IRI.  I'm going to see if I can figure out why.  I'm betting it is a similar problem to the rayDARN issue.  Let me know if you have any suggestions.

Here is the IRI output from a 2489f7e2108c9322f5030bc40376f5ef0f5781b6 run at the terminal:

```
*** IRI parameters are being calculated ***
Ne: NeQuick for Topside
Ne, foF2: URSI model is used.
Ne: B0,B1-ABT2009
Ne, foF1: probability function used.
Ne, D: IRI-90
Ne, foF2: storm model included
Te: TBT-2011 model
Auroral boundary model off
Ne, foE: storm model off
Error while reading X��@��
```

I get the same error if I run earlier commits if I don't set the DAVITPY envvar.

~Nathaniel

**Comment by w2naf** [comment]
Hey, @asreimer .  I think we need to come up with a better way to handle passing these paths to the fortran routines in the future.  It seems like a lot of work to modify all of the routines, especially when a package like IRI gets updated.  Maybe python can modify the environment before running them, rather than explicitly passing a path?  That doesn't seem like an awesome idea to me either... as I am not sure how cross-platform a solution like that would be.  Maybe @jspaleta has a suggestion?

~Nathaniel

**Comment by asreimer** [comment]
The problem is that I didn't write a "wrapper" in the `__init__.py` file in models/iri that passes the datapath to iri... For example, compare iri's current `__init__.py`: https://github.com/vtsuperdarn/davitpy/blob/enhancement_rc_params/davitpy/models/iri/__init__.py 

with the one in models/hwm: https://github.com/vtsuperdarn/davitpy/blob/enhancement_rc_params/davitpy/models/hwm/__init__.py

I just made 2 commits that should get you most of the way there. I can't be much more help today unfortunately. Last day together with my partner until October.

Also, I agree about the passing a path thing being clunky. I admit it's a bit brute force and if there's a better way I'm all for it.

**Comment by w2naf** [comment]
Hey, @asreimer. I think common blocks are the way to go with the fortran code.  It essentially creates global variables, so you don't need to pass the path explicitly through each function.  I got the IRI to work; I think we need to do the same to the HWM now.

Also, continuing down the models.ipynb notebook, I have a similar problem plotting Tsyganenko as I did with the geoPack.ipynb notebook above:

```
/usr/lib/pymodules/python2.7/mpl_toolkits/mplot3d/axes3d.pyc in grid(self, b, **kwargs)
   1254         if len(kwargs) :
   1255             b = True
-> 1256         self._draw_grid = maxes._string_to_bool(b)
   1257 
   1258     def ticklabel_format(self, **kwargs) :

AttributeError: 'module' object has no attribute '_string_to_bool'

<matplotlib.figure.Figure at 0x7f6915ac90d0>
```

That's all for tonight.  I need to spend tomorrow working on paper figures.

Best,
Nathaniel

**Comment by asreimer** [comment]
Ah yes, that is MUCH cleaner. Nice work @w2naf. I can fix up hwm and whatever else needs it, but it might be a few days.

Good luck with the figures. I start writing my next paper today.

**Comment by w2naf** [comment]
Thanks, @asreimer !  I'll keep fixing stuff up as I can and need to.  I tracked another raydarn bug down yesterday.

Have fun with your paper, too!

Nathaniel

**Comment by asreimer** [comment]
Alright, `hwm` has been modified to use the `COMMON` block method instead of the variable passing method.

How do we feel about getting this merged?

**Comment by asreimer** [comment]
Forgot to mention that a minor issue that persists is that the line added to .bashrc for the profile.bash file is added to the root .bashrc instead of the users .bashrc, but this problem will go away because we have removed the need for profile.bash in the develop branch.

**Comment by asreimer** [comment]
As we agreed, the September 1 deadline has passed so I have merged this branch into develop.

**Comment by ksterne** [comment]
Hate to bring up an old topic...but should the README be edited more with this merge?  It still has a reference to the .bashrc file as seen in:

Note that this script also modifies your ~/.bashrc file to set environment variables identifying the DaViTPy installation location, the SuperDARN database access information, and others. Because of this, please source your ~/.bashrc file (or close and reopen a new terminal window) to refresh your environment variables.

Just going through the install process on the develop branch which includes this merge and I didn't see the debian_dependencies.sh script modify my ~/.bashrc file.  Sooo.....

**Comment by asreimer** [comment]
Hey @ksterne 

Ya the README needs to be updated. Some documentation on some of the code is missing in places too. Need someone to go through and look this stuff over and fix it before the 1.0 release.

I'm currently working on fixing the RTI and fan plotting so that it is more modular and so it is easier for a user to make their own custom RTI plots (ie, make the data plotting code a separate function so a user can make a custom nxm grid of axes and plot to them, etc. or allow fan plotting to accept an existing map object and use that for plotting, thus speeding up the plotting of multiple fan plots). The code there is a bit of a mess. I'm also working on developing unit tests for every function in davitpy (this is quite time consuming it turns out...).

Can you make this README thing a new issue so it is easier to keep track of? Thanks!

**Pull request merged**
