### PR TITLE
Fetch update

### PR DESCRIPTION
**Pull request by aburrell**
Updated sdio to address several usage problems.  The changes include:

1) Allows loading data from a directory without a date structure
2) Added option to remove compressed files after uncompression.
3) Added loops to allow a total of 3 password attempts
4) Added option to consider only the specified file type (instead of trying to load any type of fit, grid, or map file)

Addresses issue #218 .

### CODE REVIEW

**Comment by aburrell** [comment]
Tests:

`import datetime as dt
import os
import davitpy.pydarn.sdio as sdio
rad = 'han'
stime = dt.datetime(2017,1,1)
etime = dt.datetime(2017,1,2)
test_command = 'ls {:s}{:04d}{:02d}{:02d}*{:s}*'.format(davitpy.rcParams['DAVIT_TMPDIR'], stime.year, stime.month, stime.day, rad)

print test_command
`
>  ls /tmp/sd/20170101*han*

`rad_ptr = sdio.radDataPtr(stime, rad, eTime=etime, fileType="fitacf", password=True)`

> 2017-01-01 00:00:00 2017-01-02 00:00:00
> Password for sd_dbread@sd-data.ece.vt.edu: 

Enter `wrong`

> WARNING:root:can't connect to sd-data.ece.vt.edu with username and password: 2 password attempts left
> Password for sd_dbread@sd-data.ece.vt.edu: 

Enter `5d`

`os.system(test_command)`

> /tmp/sd/20170101.000000.20170102.000000.han.fitacf
> /tmp/sd/20170101.0001.00.han.fitacf.bz2
> /tmp/sd/20170101.0201.00.han.fitacf.bz2
> /tmp/sd/20170101.0401.00.han.fitacf.bz2
> /tmp/sd/20170101.0601.00.han.fitacf.bz2
> /tmp/sd/20170101.0801.00.han.fitacf.bz2
> /tmp/sd/20170101.1001.00.han.fitacf.bz2
> /tmp/sd/20170101.1201.00.han.fitacf.bz2
> /tmp/sd/20170101.1401.00.han.fitacf.bz2
> /tmp/sd/20170101.1601.00.han.fitacf.bz2
> /tmp/sd/20170101.1801.00.han.fitacf.bz2
> /tmp/sd/20170101.2001.00.han.fitacf.bz2
> /tmp/sd/20170101.2201.00.han.fitacf.bz2

`os.system("rm /tmp/sd/20170101.000000.20170102.000000.han.fitacf")
rad_ptr = sdio.radDataPtr(stime, rad, eTime=etime, fileType="fitacf", src="local", local_dirfmt="/tmp/sd/", remove=True)`

> cp: /tmp/sd/20170101.0001.00.han.fitacf.bz2 and /tmp/sd/20170101.0001.00.han.fitacf.bz2 are identical (not copied).
> cp: /tmp/sd/20170101.0201.00.han.fitacf.bz2 and /tmp/sd/20170101.0201.00.han.fitacf.bz2 are identical (not copied).
> cp: /tmp/sd/20170101.0401.00.han.fitacf.bz2 and /tmp/sd/20170101.0401.00.han.fitacf.bz2 are identical (not copied).
> cp: /tmp/sd/20170101.0601.00.han.fitacf.bz2 and /tmp/sd/20170101.0601.00.han.fitacf.bz2 are identical (not copied).
> cp: /tmp/sd/20170101.0801.00.han.fitacf.bz2 and /tmp/sd/20170101.0801.00.han.fitacf.bz2 are identical (not copied).
> cp: /tmp/sd/20170101.1001.00.han.fitacf.bz2 and /tmp/sd/20170101.1001.00.han.fitacf.bz2 are identical (not copied).
> cp: /tmp/sd/20170101.1201.00.han.fitacf.bz2 and /tmp/sd/20170101.1201.00.han.fitacf.bz2 are identical (not copied).
> cp: /tmp/sd/20170101.1401.00.han.fitacf.bz2 and /tmp/sd/20170101.1401.00.han.fitacf.bz2 are identical (not copied).
> cp: /tmp/sd/20170101.1601.00.han.fitacf.bz2 and /tmp/sd/20170101.1601.00.han.fitacf.bz2 are identical (not copied).
> cp: /tmp/sd/20170101.1801.00.han.fitacf.bz2 and /tmp/sd/20170101.1801.00.han.fitacf.bz2 are identical (not copied).
> cp: /tmp/sd/20170101.2001.00.han.fitacf.bz2 and /tmp/sd/20170101.2001.00.han.fitacf.bz2 are identical (not copied).
> cp: /tmp/sd/20170101.2201.00.han.fitacf.bz2 and /tmp/sd/20170101.2201.00.han.fitacf.bz2 are identical (not copied).
> cp: /tmp/sd/20170102.0001.00.han.fitacf.bz2 and /tmp/sd/20170102.0001.00.han.fitacf.bz2 are identical (not copied).

`os.system(test_command)`
> /tmp/sd/20170101.000000.20170102.000000.han.fitacf

`os.system("rm /tmp/sd/20170101.000000.20170102.000000.han.fitacf")
rad_ptr = sdio.radDataPtr(stime, rad, eTime=etime, fileType='lmfit')`

> 2017-01-01 00:00:00 2017-01-02 00:00:00
> WARNING:root:cannot access [data/2017/lmfit/han/]
> WARNING:root:cannot access [data/2016/lmfit/han/]
> ...
> WARNING:root:cannot access [data/2015/lmfit/han/]
> WARNING:root:cannot access [data/2017/lmfit/han/]
> 2017-01-01 00:00:00 2017-01-02 00:00:00

`os.system(test_command)`
> /tmp/sd/20170101.000000.20170102.000000.han.fitex
> /tmp/sd/20170101.0001.00.han.fitex.bz2
> /tmp/sd/20170101.0201.00.han.fitex.bz2
> /tmp/sd/20170101.0401.00.han.fitex.bz2
> /tmp/sd/20170101.0601.00.han.fitex.bz2
> /tmp/sd/20170101.0801.00.han.fitex.bz2
> /tmp/sd/20170101.1001.00.han.fitex.bz2
> /tmp/sd/20170101.1201.00.han.fitex.bz2
> /tmp/sd/20170101.1401.00.han.fitex.bz2
> /tmp/sd/20170101.1601.00.han.fitex.bz2
> /tmp/sd/20170101.1801.00.han.fitex.bz2
> /tmp/sd/20170101.2001.00.han.fitex.bz2
> /tmp/sd/20170101.2201.00.han.fitex.bz2

`rad_ptr = sdio.radDataPtr(stime, rad, eTime=etime, fileType='lmfit', try_file_types=False)`

> 2017-01-01 00:00:00 2017-01-02 00:00:00
> WARNING:root:cannot access [data/2017/lmfit/han/]
> WARNING:root:cannot access [data/2016/lmfit/han/]
> ...
> WARNING:root:cannot access [data/2015/lmfit/han/]
> WARNING:root:cannot access [data/2017/lmfit/han/]
> ERROR:root:Sorry, we could not find any data for you :(

**Comment by aburrell** [comment]
Hi @MuhammadVT , @SibusisoMthembu ,

I've assigned you as testers in the hope that one of you could fit testing for this within the month.

**Comment by Shirling-VT** [comment]
@aburrell 

I just tested the codes and have a few feedback:  1. I didn't have the "davitpy" environment variable set, so I just replace "davitpy.rcParams['DAVIT_TMPDIR']" with "/tmp/sd/" and it works; 2. For rad_ptr = sdio.radDataPtr(stime, rad, eTime=etime, fileType="fitacf", password=True), it seems that I don't need to enter the password, because my computer is mounted to the VT data server? Therefore, I cannot test the three attempts of password input. 3. For all other commands, I get similar results with yours.

**Comment by MuhammadVT** [comment]
Hi @aburrell 
I have gotten all the expected results for the different testings, including the three password attempts. Merging it....

**Pull request merged**
