### PR TITLE
Improve Non-VT Database use

### PR DESCRIPTION
**Pull request by aburrell**
Added two parameters to rcsetup, which allows users to specify
different databases for datafiles and hardware files.

Summary of changes:
davitpyrc: 
    1) added keywords SDBREADUSER, SDBREADPASS
    2) changed default for AACGM_DAVITPY_DAT_PREFIX to be more intuitive
    3) PEP8 compliance

rcsetup:
    1) added keywords SDBREADUSER, SDBREADPASS
    2) PEP8 compliance

pydarn/radar/radInfoIo.py:
    1) Lines 254-257 changed from DBREADUSER/PASS to SDBREADUSER/PASS
    2) a lot of PEP8 compliance changes.

Testing:
- If you use VT, set up using defaults and ensure you can still download data and load hardware info
- If you don't use VT, change the DBREADUSER defaults to your own server and load data from there.  Then use VT to load the hardware info.

### CODE REVIEW

**Comment by asreimer** [comment]
I've tested this code. Here's what I did and what I found:

1) `AACGM_DAVITPY_DAT_PREFIX` gets set to `/davitpy_dir_path/tables/aacgm/aacgm_coeffs/` in `davitpy.rcParams`. This shouldn't happen and is fixed by commenting out [this line](https://github.com/aburrell/davitpy/blob/non-VT-database/davitpy/davitpyrc#L73) in the `davitpyrc` file.

2) The `davitpy/gme/sat/rbsp.py` contains a `DBREADUSER` and `DBREADPASS`. I think these should be changed over to the new `SDBREADUSER`. Also, there are some of these in `davitpy/pydarn/sdio/dbUtils.py`. @aburrel, since this is being pulled from your own repo, could you make these changes? Here's all the relevant lines of code: [1](https://github.com/aburrell/davitpy/blob/non-VT-database/davitpy/gme/sat/rbsp.py#L54-L55), [2](https://github.com/aburrell/davitpy/blob/non-VT-database/davitpy/pydarn/sdio/dbUtils.py#L25), [3](https://github.com/aburrell/davitpy/blob/non-VT-database/davitpy/pydarn/sdio/dbUtils.py#L67), [4](https://github.com/aburrell/davitpy/blob/non-VT-database/davitpy/pydarn/sdio/dbUtils.py#L115).

Besides these minor things, I didn't have any trouble using this pull request! 

As a reminder, we will need to make sure #171 gets merged before we merge this one.

**Comment by aburrell** [comment]
Changes made.

**Comment by MuhammadVT** [comment]
I have run radarStruct.ipynb and radDataRead.ipynb to test this pull
request (with default settings). They are working fine.

**Comment by asreimer** [comment]
Everything looks good from my end. I also ran radarStruct and radDataRead ipython notebooks without issue. 

@aburrell the only thing left to do is resolve the merge conflicts in `radInfoIo.py` due to the PEP-8 edits you made. Could you pull in the current develop branch and resolve the conflicts? Then I'll have a look and merge this.

**Comment by aburrell** [comment]
No idea how to resolve these conflicts.  I've asked github support for help, we'll see what happens.

**Comment by ksterne** [comment]
Hey @aburrell, if you wanted, you could pull your branch in to the vtsuperdarn repository so that others might be able to look at it and maybe help out.

**Comment by aburrell** [comment]
Alright!  That was incredibly painful, but will hopefully make things easier in the future.  Ready for someone to merge.

**Comment by aburrell** [comment]
@ksterne I would have if I could have!  But I think this works now...

**Comment by asreimer** [comment]
Sweet, now this can be merged. 

But before it is, I have one question regarding changes to the doc strings in `radInfoIo`. Specifically, why were the changes made? This introduces a different docstring style that is inconsistent with the rest of the docstrings in davitpy and I would much rather see a separate docstring pull request changing everything everywhere if we want to change docstring style.

For example, line 29 of radInfoIo is changed from:

    **Args***

to

    Parameters
    ----------

I think these docstring changes should be reverted.

**Comment by aburrell** [comment]
I made the changes because ages ago we decided to follow numpy formatting for comments.  So I made a few changes and then got tired of it and quit.  I'm happy to revert those for now.

**Comment by asreimer** [comment]
Ah that's right... Jeeze, that was a long time ago haha.

Maybe we can make a docstring change push before the next release? The idea is that we would freeze allowing new pull requests, work on merging in the ones we have, and then make changes to the docstrings. Simultaneously, we can replace print statements with the `logging` module.

**Comment by aburrell** [comment]
That works for me!  I can make this change tomorrow.

**Comment by asreimer** [comment]
I'm all flip floppy today... Just leave the the docstring stuff as is @aburrell since we are going to make a push before the next release.

**Comment by aburrell** [comment]
Sounds good.

**Comment by asreimer** [comment]
I did some basic testing again here and everything is good. Merging.

**Pull request merged**
